### ISSUE TITLE
Failed to find required executable systemctl in paths

### ISSUE THREAD

**Issue by paulcalabro** [wazuh/wazuh-ansible#102]
The role _README_ files state support for Ubuntu, however, they don't state _which versions_ of Ubuntu are supported. That being said, I've come across an issue with Ubuntu 14.04 servers where the following error message occurs:

```
msg: 'Failed to find required executable systemctl in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin'
```
This is caused by the following task:

```
- name: Reload systemd
  systemd: daemon_reload=yes
  ignore_errors: yes
when: not (ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA")
```

According to this reference:

https://en.wikipedia.org/wiki/Systemd

Systemd wasn't the default service manager until **v15.04**. You'll probably want to account for that in your conditional logic.

**Comment by cadoming** [comment]
Hi @paulcalabro,

I created the PR #114 that solved this Issue and also solve the problem for debian < 8.  Thank you for your collaboration.

Regards,
Carlos
