### ISSUE TITLE
Error: ansible.errors.AnsibleUndefinedVariable: 'None' has no attribute 'name'. 'None' has no attribute 'name'

### ISSUE THREAD

**Issue by AndreasHadjivasili** [wazuh/wazuh-ansible#1066]
Hello, i am kinda newbie in ansible and deploying services with it. I am trying to deploy a wazuh cluster and i am getting the following error: 

TASK [../roles/wazuh/wazuh-indexer : Copy Opensearch Configuration File] *******************
task path: /etc/ansible/roles/wazuh-ansible/roles/wazuh/wazuh-indexer/tasks/main.yml:42
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/template/__init__.py", line 987, in do_template
    res = self.environment.concat(rf)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ansible/template/native_helpers.py", line 88, in ansible_concat
    return ''.join([to_text(v) for v in nodes])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ansible/template/native_helpers.py", line 88, in <listcomp>
    return ''.join([to_text(v) for v in nodes])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 59, in root
  File "/usr/lib/python3/dist-packages/ansible/template/__init__.py", line 262, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ansible/template/__init__.py", line 511, in _ansible_finalize
    return thing if _fail_on_undefined(thing) is not None else ''
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ansible/template/__init__.py", line 483, in _fail_on_undefined
    elif is_sequence(data):
         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ansible/module_utils/common/collections.py", line 94, in is_sequence
    if not include_strings and is_string(seq):
  File "/usr/lib/python3/dist-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/plugins/action/template.py", line 141, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ansible/template/__init__.py", line 1021, in do_template
    raise AnsibleUndefinedVariable(e, orig_exc=e)
ansible.errors.AnsibleUndefinedVariable: 'None' has no attribute 'name'. 'None' has no attribute 'name'

Can anyone faced the same issue or knows what is the problem. I can provide any config or more information needed.

Thank you in advance!

**Comment by AndreasHadjivasili** [comment]
Hello David,

So i am actually following the Documentation https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/index.html, specifically the "Install a Wazuh cluster" Doc  and based on that i have the following files created:

hosts:

indexer1 ansible_host=192.168.223.130 private_ip=192.168.223.130 indexer_node_name=node-index-10
indexer2 ansible_host=192.168.223.131 private_ip=192.168.223.131 indexer_node_name=node-index-20
indexer8 ansible_host=192.168.223.133 private_ip=192.168.223.133 indexer_node_name=node-index-80
indexer9 ansible_host=192.168.223.132 private_ip=192.168.223.132 indexer_node_name=node-index-90
dashboard  ansible_host=192.168.223.131 private_ip=192.168.223.131 indexer_node_name=node-dash-20
manager ansible_host=192.168.223.131 private_ip=192.168.223.131 indexer_node_name=node-manager-20
worker1 ansible_host=192.168.223.130 private_ip=192.168.223.130 indexer_node_name=node-worker-10
worker2 ansible_host=192.168.223.131 private_ip=192.168.223.131 indexer_node_name=node-worker-20
worker8 ansible_host=192.168.223.133 private_ip=192.168.223.133 indexer_node_name=node-worker-80
worker9 ansible_host=192.168.223.132 private_ip=192.168.223.132 indexer_node_name=node-worker-90

[wi_cluster]
worker1
worker2
worker8
worker9
[all:vars]

ansible_ssh_user=MyUser
ansible_ssh_private_key_file=dirToKey
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'

production.yml
# Certificates generation
  - hosts: worker2
    roles:
      - role: ../roles/wazuh/wazuh-indexer
        indexer_network_host: "192.168.223.131"
        indexer_cluster_nodes:
          - "192.168.223.130"
          - "192.168.223.131"
          - "192.168.223.132"
          - "192.168.223.133"
        indexer_discovery_nodes:
          - "192.168.223.130"
          - "192.168.223.131"
          - "192.168.223.132"
          - "192.168.223.133"
        perform_installation: false
    become: no
    vars:
      indexer_node_master: true
      instances:
        node1:
          name: node-index-10       # Important: must be equal to indexer_node_name.
          ip: "192.168.223.130"   # When unzipping, the node will search for its node name folder to get the cert.
          role: indexer
        node2:
          name: node-index-20
          ip: "192.168.223.131"
          role: indexer
        node3:
          name: node-index-90
          ip: "192.168.223.132"
          role: indexer
        node4:
          name: node-index-80
          ip: "192.168.223.133"
          role: indexer
        node5:
          name: node-manager-20
          ip: "192.168.223.131"
          role: wazuh
          node_type: master
        node6:
          name: node-worker-10
          ip: "192.168.223.130"
          role: wazuh
          node_type: worker
        node7:
          name: node-worker-90
          ip: "192.168.223.132"
          role: wazuh
          node_type: worker
        node8:
          name: node-wokrer-80
          ip: "192.168.223.133"
          role: wazuh
          node_type: worker
        node9:
          name: node-dash-20
          ip: "192.168.223.131"
          role: dashboard
    tags:
      - generate-certs

# Wazuh indexer cluster
  - hosts: wi_cluster
    strategy: free
    roles:
      - role: ../roles/wazuh/wazuh-indexer
        indexer_network_host: "192.168.223.131"
    become: yes
    become_user: root
    vars:
      indexer_cluster_nodes:
          - "192.168.223.130"
          - "192.168.223.131"
          - "192.168.223.132"
          - "192.168.223.133"
      indexer_discovery_nodes:
          - "192.168.223.130"
          - "192.168.223.131"
          - "192.168.223.132"
          - "192.168.223.133"
      indexer_node_master: true
      instances:
        instances:
        node1:
          name: node-index-10       # Important: must be equal to indexer_node_name.
          ip: "192.168.223.130"   # When unzipping, the node will search for its node name folder to get the cert.
          role: indexer
        node2:
          name: node-index-20
          ip: "192.168.223.131"
          role: indexer
        node3:
          name: node-index-90
          ip: "192.168.223.132"
          role: indexer
        node4:
          name: node-index-80
          ip: "192.168.223.133"
          role: indexer
        node5:
          name: node-manager-20
          ip: "192.168.223.131"
          role: wazuh
          node_type: master
        node6:
          name: node-worker-10
          ip: "192.168.223.130"
          role: wazuh
          node_type: worker
        node7:
          name: node-worker-90
          ip: "192.168.223.132"
          role: wazuh
          node_type: worker
        node8:
          name: node-wokrer-80
          ip: "192.168.223.133"
          role: wazuh
          node_type: worker
        node9:
          name: node-dash-20
          ip: "192.168.223.131"
          role: dashboard

# Wazuh cluster
  - hosts: manager
    roles:
      - role: "../roles/wazuh/ansible-wazuh-manager"
      - role: "../roles/wazuh/ansible-filebeat-oss"
        filebeat_node_name: node-manager-20
    become: yes
    become_user: root
    vars:
      wazuh_manager_config:
        connection:
            - type: 'secure'
              port: '1514'
              protocol: 'tcp'
              queue_size: 131072
        api:
            https: 'yes'
        cluster:
            disable: 'no'
            node_name: 'master'
            node_type: 'master'
            key: 'c98b62a9b6169ac5f67dae55ae4a9088'
            nodes:
                - "192.168.223.131"
            hidden: 'no'
      wazuh_api_users:
        - username: admin
          password: SecretPassword1!
      filebeat_output_indexer_hosts:
              - "192.168.223.130"
              - "192.168.223.131"
              - "192.168.223.132"
              - "192.168.223.133"

  - hosts: worker1
    roles:
      - role: "../roles/wazuh/ansible-wazuh-manager"
      - role: "../roles/wazuh/ansible-filebeat-oss"
        filebeat_node_name: node-worker-10
    become: yes
    become_user: root
    vars:
      wazuh_manager_config:
        connection:
            - type: 'secure'
              port: '1514'
              protocol: 'tcp'
              queue_size: 131072
        api:
            https: 'yes'
        cluster:
            disable: 'no'
            node_name: 'worker_10'
            node_type: 'worker'
            key: 'c98b62a9b6169ac5f67dae55ae4a9088'
            nodes:
                - "192.168.223.131"
            hidden: 'no'
      filebeat_output_indexer_hosts:
              - "192.168.223.130"
              - "192.168.223.131"
              - "192.168.223.132"
              - "192.168.223.133"

  - hosts: worker8
    roles:
      - role: "../roles/wazuh/ansible-wazuh-manager"
      - role: "../roles/wazuh/ansible-filebeat-oss"
        filebeat_node_name: node-worker-80
    become: yes
    become_user: root
    vars:
      wazuh_manager_config:
        connection:
            - type: 'secure'
              port: '1514'
              protocol: 'tcp'
              queue_size: 131072
        api:
            https: 'yes'
        cluster:
            disable: 'no'
            node_name: 'worker_80'
            node_type: 'worker'
            key: 'c98b62a9b6169ac5f67dae55ae4a9088'
            nodes:
                - "192.168.223.131"
            hidden: 'no'
      filebeat_output_indexer_hosts:
              - "192.168.223.130"
              - "192.168.223.131"
              - "192.168.223.132"
              - "192.168.223.133"

  - hosts: worker90
    roles:
      - role: "../roles/wazuh/ansible-wazuh-manager"
      - role: "../roles/wazuh/ansible-filebeat-oss"
        filebeat_node_name: node-worker-90
    become: yes
    become_user: root
    vars:
      wazuh_manager_config:
        connection:
            - type: 'secure'
              port: '1514'
              protocol: 'tcp'
              queue_size: 131072
        api:
            https: 'yes'
        cluster:
            disable: 'no'
            node_name: 'worker_90'
            node_type: 'worker'
            key: 'c98b62a9b6169ac5f67dae55ae4a9088'
            nodes:
                - "192.168.223.131"
            hidden: 'no'
      filebeat_output_indexer_hosts:
              - "192.168.223.130"
              - "192.168.223.131"
              - "192.168.223.132"
              - "192.168.223.133"

# Indexer + dashboard node
  - hosts: dashboard
    roles:
      - role: "../roles/wazuh/wazuh-indexer"
      - role: "../roles/wazuh/wazuh-dashboard"
    become: yes
    become_user: root
    vars:
      indexer_network_host: "192.168.223.131"
      indexer_node_name: node-dash-20
      indexer_node_master: false
      indexer_node_ingest: false
      indexer_node_data: false
      indexer_cluster_nodes:
              - "192.168.223.130"
              - "192.168.223.131"
              - "192.168.223.132"
              - "192.168.223.133"
      indexer_discovery_nodes:
              - "192.168.223.130"
              - "192.168.223.131"
              - "192.168.223.132"
              - "192.168.223.133"
      dashboard_node_name: node-6
      wazuh_api_credentials:
        - id: default
          url: https://192.168.223.131
          port: 55000
          username: admin
          password: SecretPassword1!
      instances:
        node1:
          name: node-index-10       # Important: must be equal to indexer_node_name.
          ip: "192.168.223.130"   # When unzipping, the node will search for its node name folder to get the cert.
          role: indexer
        node2:
          name: node-index-20
          ip: "192.168.223.131"
          role: indexer
        node3:
          name: node-index-90
          ip: "192.168.223.132"
          role: indexer
        node4:
          name: node-index-80
          ip: "192.168.223.133"
          role: indexer
        node5:
          name: node-manager-20
          ip: "192.168.223.131"
          role: wazuh
          node_type: master
        node6:
          name: node-worker-10
          ip: "192.168.223.130"
          role: wazuh
          node_type: worker
        node7:
          name: node-worker-90
          ip: "192.168.223.132"
          role: wazuh
          node_type: worker
        node8:
          name: node-wokrer-80
          ip: "192.168.223.133"
          role: wazuh
          node_type: worker
        node9:
          name: node-dash-20
          ip: "192.168.223.131"
          role: dashboard
      ansible_shell_allow_world_readable_temp: true

Thank you

**Comment by davidcr01** [comment]
Thank you for your configuration file. It seems correct for me. 
Investigating the behavior on the playbook, the error is generated in the following task:

```yml
- name: Copy Opensearch Configuration File
      template:
        src: "templates/opensearch.yml.j2"
        dest: "{{ indexer_conf_path }}/opensearch.yml"
        owner: root
        group: wazuh-indexer
        mode: 0640
        force: yes
      tags: install
```

In the `opensearch.yml.j2` file, I see the following variables:
```j2
network.host: {{ indexer_network_host }}
node.name: {{ indexer_node_name }}
{% if single_node == true %}
discovery.type: single-node
{% else %}
cluster.initial_master_nodes:
{% for item in indexer_cluster_nodes %}
  - {{ item }}
{% endfor %}

discovery.seed_hosts:
{% for item in indexer_discovery_nodes %}
  - {{ item }}
{% endfor %}
{% endif %}

cluster.name: {{ indexer_cluster_name }}
```

All these variables closed with "{{}}" are in your configuration file. However, the `indexer_cluster_name` variable is not located in this file, and maybe this is causing the error.

Could you please check if this variable is defined correctly in the  `roles/wazuh/wazuh-indexer/defaults/main.yml` file?

**Comment by teddytpc1** [comment]
Hi.
I noticed that you have a duplicated `instances` definition in the Wazuh indexer cluster part of the playbook.
Please remove the second occurrence:
![Screenshot from 2023-10-11 14-19-38](https://github.com/wazuh/wazuh-ansible/assets/33964202/3d40dfb8-8fd6-431f-89be-701baca1d2b8)


Also, the `indexer_network_host` is intended to be the current host `private_ip` (the one defined in the inventory). I see that you have a fixed IP for all the Indexer hosts. Please, check the [wazuh-production-ready.yml](https://github.com/wazuh/wazuh-ansible/blob/v4.5.3/playbooks/wazuh-production-ready.yml) playbook for reference.
