### ISSUE TITLE
Update Configuration to New Vulnerability Detector and Indexer

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh-ansible#1159]
**Description:**

This issue focuses on updating the configuration settings for the vulnerability detector and indexer modules to align with the new templates. The old configuration for vulnerability detection will be removed, and the settings will be replaced with those described in the following templates:

- [Vulnerability Detector Configuration](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/etc/templates/config/generic/wodle-vulnerability-detection.manager.template)
- [Indexer Configuration](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/etc/templates/config/generic/wodle-indexer.manager.template)

**User Stories:**

- As a system administrator, I want the configuration to be up-to-date with the new vulnerability detection and indexing templates to ensure optimal functionality.
- As a developer, I want to remove the old configuration settings and replace them with the new templates to maintain consistency and improve maintainability.

**Tasks:**

1. Review New Configuration Templates:
   - Examine the provided vulnerability detector and indexer configuration templates thoroughly.

2. Identify Old Configuration Settings:
   - Identify the old configuration settings that need to be removed.

3. Replace Old Settings with New Templates:
   - Implement the new configuration settings from the provided templates.

**Definition of Done:**

- The old configuration settings have been removed.
- The new configuration settings from the provided templates have been implemented.

**Comment by teddytpc1** [comment]
## Analysis
The following section should be removed:
https://github.com/wazuh/wazuh-automation/blob/63d030265717e666ced836731483d58a2c9ee393/aws/demo-environment/roles/use_cases/tasks/vulnerability_detector.yml#L3-L104

**Comment by davidcr01** [comment]
# Update Report

After performing some changes on the code:
- Duplicating some necessary variables from the `ansible-filebeat-oss` role to the `ansible-wazuh-manager` role.
- Modifying the vulnerability detector configuration.
- Adding the indexer configuration.

And after performing a test using the Wazuh single playbook, the Wazuh stack is correctly installed, and the `ossec.conf` file looks like this:

```conf
<vulnerability-detection>
    <enabled>yes</enabled>
    <indexer-status>yes</indexer-status>
    <feed-update-interval>60m</feed-update-interval>
  </vulnerability-detection>

  <indexer>
    <enabled>yes</enabled>
    <hosts>
   
      <host>https://['127.0.0.1']:9200</host>
   
    </hosts>

    <username>admin</username>
    <password>"changeme"</password>
    <ssl>
      <certificate_authorities>
        <ca>/etc/pki/filebeat/root-ca.pem</ca>
      </certificate_authorities>
      <certificate>/etc/pki/filebeat/node-1.pem</certificate>
      <key>/etc/pki/filebeat/node-1-key.pem</key>
    </ssl>
  </indexer>
```

It is necessary to:

- [ ] Fix the host IP configuration
- [ ] Fix the double quotes of the password value
