### ISSUE TITLE
Review and fix the Wazuh version references in 4.8 and 4.9 branches

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-ansible#1187]
A [community user](https://github.com/wazuh/wazuh-ansible/issues/1173) has reported to us that when deploying Wazuh through Ansible, an attempt is made to download the 4.8 version certificate script. This is because the `master` branch is not updated to 4.9 version

https://github.com/wazuh/wazuh-ansible/blob/b13cf47f873af2839ee254273a2fc4cf7787141f/roles/wazuh/vars/repo.yml#L16

It is necessary to review the 4.8.x and master branches to ensure that all version references are correct

**Comment by davidcr01** [comment]
# Update Report

- Reviewed 4.8.0 branch. No references were found.
- Reviewed 4.8.1 branch. No references were found.
- Reviewed 4.8.2 branch. No references were found.
- References in the master branch were found as @rauldpm reported.
