### ISSUE TITLE
Rollback ISM changes

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-ansible#1213]
## Description

Parent issue: https://github.com/wazuh/wazuh-automation/issues/1558
Continuing https://github.com/wazuh/wazuh-indexer/issues/150, we are rolling back the rollover+alias project from the 4.8.0 release, We'll revisit this for the next major release 5.0.0.

## Tasks
- [ ] Rollback the ISM changes in `wazuh-ansible`:
    Related PRs:
    - https://github.com/wazuh/wazuh-ansible/pull/1110
    
## Related:
- https://github.com/wazuh/internal-devel-requests/issues/781

**Comment by teddytpc1** [comment]
Changes are being tested with the Demo deployment.

**Comment by teddytpc1** [comment]
The Demo deployment pipeline succeeded but it was necessary to create a new index pattern to see the alerts. This issue was caused by the Filebeat module version that is going to be updated.
