### ISSUE TITLE
Move variables found in vars/*.yml files to default/main.yml

### ISSUE THREAD

**Issue by paulcalabro** [wazuh/wazuh-ansible#123]
**Problem**: it's not easy to override variables found in _vars/*.yml_ because they have a fairly high precedence. For example, if you use inventory or group vars, a very common practice, you're not able to override these variables. A better place is to use to _default/main.yml_, which has a lower precedence. 

https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by paulcalabro** [comment]
The issue I'm having is that I have to comment these files out, in order to override the variables they define. Ideally, I should be able to override them using group_vars or host_vars and leave the code untouched.

**Comment by paulcalabro** [comment]
A good example of when to use vars/*.yml files might be for platform specific stuff...things likely not to be overridden by someone using the code:

e.g. _ubuntu.yml_:

```
---
packages:
  - wazuh-manager=3.7.2-1
  - wazuh-api=3.7.2-1
  - expect=5.45-5ubuntu1
```

**Comment by singuliere** [comment]
Surprisingly (or not ;-) I just [proposed a pull request to resolve that issue](https://github.com/wazuh/wazuh-ansible/issues/123).

**Comment by paulcalabro** [comment]
Nice! Thanks for doing that. That's probably a good approach since it's consistent with the other vars files.

**Comment by jm404** [comment]
Hi @singuliere , @paulcalabro ,

I'm closing this as we no longer use `vars` folder to declare variables.

Best regards,

Jose
