### ISSUE TITLE
wazuh agent registration must not delegate_to localhost

### ISSUE THREAD

**Issue by singuliere** [wazuh/wazuh-ansible#126]
# Context

When the agent registers, the API call to get information about it [delegate_to: localhost](https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml#L120). 

# Problem

When the wazuh manager is behind a firewall that does not allow the ansible controller access to the API port 55000, the call will timeout and the registration will fail.

**Comment by paulcalabro** [comment]
That's a fair argument for keeping it. If that could be made configurable, it would be ideal.

**Comment by singuliere** [comment]
@angystardust thanks for the explanation, it makes perfect sense. It currently is inconsistent (because 689bb8ff35b38fa8258f82db219a4d2565dc5239 removed one delegate_to and not the other) and I wrongly assumed the right solution was the one matching my own use case.

Since @paulcalabro seems to agree with the idea of making it configurable, I'll amend the pull request accordingly.
