### ISSUE TITLE
Unified certificate paths for filebeat: Aligning ansible installation method with standard configuration

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-ansible#1285]
## Description

Currently, we're utilizing the repository `/etc/pki/filebeat` to house Filebeat certificates:

https://github.com/wazuh/wazuh-ansible/blob/ba756877dc6e2a68f7772640a75283387e9be487/roles/wazuh/ansible-filebeat-oss/defaults/main.yml#L19

This approach, however, presents several issues:

- **Lack of consistency with the default certificate path**: While the current setup directs certificates to `/etc/pki/`, the standard location across other installation methods is `/etc/filebeat/certs/`. This inconsistency can cause confusion for users trying to follow the documentation. Ensuring uniformity in directory configurations is crucial, especially now that this configuration is integrated into the indexer module of the manager.
- **Platform-specific path usage**: The `/etc/pki/` path is tailored for Red Hat systems. However, this configuration is applied across all host operating systems. For instance, on Ubuntu, the anticipated path should be `/etc/ssl/certs/` instead.

**Comment by davidjiglesias** [comment]
We might remove Filebeat in 5.0.0
