### ISSUE TITLE
openscap should default to <scan_on_start>no</scan_on_start>

### ISSUE THREAD

**Issue by singuliere** [wazuh/wazuh-ansible#139]
By default [openscap is set to scan_on_start](https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-agent/defaults/main.yml#L78). It should be set to **no** instead because [it requires a lot of CPU and RAM](https://github.com/wazuh/wazuh/issues/2331) and is very likely to cause problems at boot time on production systems, either because the processes timeout or because they run out of memory.

**Comment by jm404** [comment]
Hi @singuliere ,

This is now disabled by default https://github.com/wazuh/wazuh-ansible/blob/719e0fb8ce972dc176855edc603dce5cfb7958ba/roles/wazuh/ansible-wazuh-manager/defaults/main.yml#L194

I'm closing this issue as this is already implemented. Please feel free to open a new one if you need it.

Best regards,

Jose
