### ISSUE TITLE
Test the Wazuh Ansible deployment. Verify it installs the 4.9.0-2 package.

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-ansible#1401]
related: https://github.com/wazuh/wazuh-automation/issues/1830

## Description

Due to a bug found after the 4.9.0, a new revision (2) for the wazuh-dashboard will be released. We will need to perform some tests with Wazuh installation assistant to ensure that the correct package of Wazuh dashboard is installed.

## Test

- [x] Test Single Node installation in DEB distribution 
- [x] Test Single Node installation in RPM distribution

**Comment by teddytpc1** [comment]
The RPM packages will be tested with the Demo deployment [here](https://ci.wazuh.info/job/Procedure_deploy_demo/513/).

**Comment by teddytpc1** [comment]
## Ubuntu
The Wazuh dashboard installation was tested with Ansible and it installs the correct version (`4.9.0-2`):
```BASH
apt list --installed | grep wazuh

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

wazuh-dashboard/unstable,now 4.9.0-2 amd64 [installed]
```

**Comment by teddytpc1** [comment]
## AL2023
The Wazuh dashboard installation was tested with Ansible (and the Demo deployment pipeline) and it installs the correct version (`4.9.0-2`):
```BASH
rpm -qa | grep wazuh
wazuh-indexer-4.9.0-1.x86_64
wazuh-dashboard-4.9.0-2.x86_64
```

**Comment by c-bordon** [comment]
LGTM
