### ISSUE TITLE
Upgrade Wazuh minor version tests

### ISSUE THREAD

**Issue by cadoming** [wazuh/wazuh-ansible#142]
# Testing: Upgrade Wazuh minor version

| Version | Revision | Branch |
| --- | --- | --- |
| 3.8.0_6.5.4 | 3800 | 3.8.0_6.5.4 |

## Basic tests

- [x] Deployment of the Wazuh-manager in different environments.
  - [x] Ubuntu 18.04.
  - [x] Ubuntu 14.04.
  - [x] CentOS 7. 
  - [x] Amazon Linux.
- [x] Deployment of the Wazuh-agent in different environments.
  - [x] Ubuntu 18.04. 
    - [x] Agent registration. 
    - [x] Check the flow of the alerts. 
  - [x] Ubuntu 14.04. 
    - [x] Agent registration. 
    - [x] Check the flow of the alerts. 
  - [x] CentOS 7. 
    - [x] Agent registration. 
    - [x] Check the flow of the alerts. 
  - [x] Amazon Linux.
    - [x] Agent registration.
    - [x] Check the flow of the alerts.  
  - [x] Windows 7. 
    - [x] Agent registration. 
    - [x] Check the flow of the alerts. 
	
- [x] Upgrade of the Wazuh-manager in different environments.
  - [x] Ubuntu 18.04.
  - [x] Ubuntu 14.04.
  - [x] CentOS 7. 
  - [x] Amazon Linux.
- [x] Upgrade of the Wazuh-agent in different environments.
  - [x] Ubuntu 18.04. 
    - [x] Agent registration. 
    - [x] Check the flow of the alerts. 
  - [x] Ubuntu 14.04. 
    - [x] Agent registration. 
    - [x] Check the flow of the alerts. 
  - [x] CentOS 7. 
    - [x] Agent registration. 
    - [x] Check the flow of the alerts.  
  - [x] Amazon Linux.
    - [x] Agent registration.
    - [x] Check the flow of the alerts.  
  - [x] Windows 7. 
    - [x] Agent registration.  
    - [x] Check the flow of the alerts. 

- [x] Deployment of the Wazuh app

**Comment by paulcalabro** [comment]
Is it possible to add `Ubuntu 14.04` in these tests? Do you support all LTS releases?

**Comment by cadoming** [comment]
Hi @paulcalabro,

We will include `Ubuntu 14.04`, thanks for the propousal.

**Comment by paulcalabro** [comment]
Thanks @cadoming !
