### ISSUE TITLE
 Need the ability to install an agent, but not register it

### ISSUE THREAD

**Issue by paulcalabro** [wazuh/wazuh-ansible#149]
Sometimes it's necessary to install the Wazuh agent, but not register it with a manager. For example, when working with Amazon Machine Images (AMIs). You want to reduce the time it takes to install the agent by baking the installation into the image, however, you don't want to have duplicate client.keys files by doing registration at the time of image creation. Having the ability to filter these tasks would be useful, perhaps with tags.

**Comment by Zenidd** [comment]
Hi @paulcalabro,

First of all, we're very sorry for the late response. Your idea is very interesting and it is great that you also propose an implementation based on tags. We are going to study the implementation of this functionality and we will let you know more about it.

Again, thank you for contributing to our project.
<br></br>
Best regards,

Juan Pablo Sáez

**Comment by xr09** [comment]
Hi @paulcalabro ,

I see there's already a tag `config` in the agent playbook.

Could you try with `--skip-tags config` when running the playbook.

Regards.
