### ISSUE TITLE
Agent install fails with async task did not complete within the requested time

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh-ansible#171]
Received the following on 18.04 install:
TASK [ansible-wazuh-agent : Linux | Install wazuh-agent] *************************************************************************************************************************************
task path: /<path>/wazuh-ansible/roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml:8
fatal: [192.168.x.x]: FAILED! => {"changed": false, "msg": "async task did not complete within the requested time"}

**Comment by jm404** [comment]
Hello @alphaDev23,

Thank you for reporting this issue! It looks like the installation of the wazuh-agent is not getting completed in time.
Could you provide more information about which environment are you working with? (VM, low-end PC)? And which version of ansible are you running? 

I also suggest you to modify the **poll** value that specifies the timeout value. 
https://github.com/wazuh/wazuh-ansible/blob/f527db79f7cf7872f2f77d7a8907bb6e3d919d28/roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml#L8-L13

You can find more information in https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html

Regards!

**Comment by manuasir** [comment]
Solved here: https://github.com/wazuh/wazuh-ansible/pull/180
