### ISSUE TITLE
SSL configuration section missing in filebeat.yml jinja2 template

### ISSUE THREAD

**Issue by M-Golyani** [wazuh/wazuh-ansible#176]
Hi there :o)

Not so sure whether this is a feature request or a BUG or something else.

In a distributed architecture implementation, where ELK server and WAZUH manager node are on different machines, it is suggested to secure the connection between Filebeat (which is installed on Manager node), and Logstash (which is installed on ELK server).

To do so, the current documentation of Filebeat provides us with "SSL" options [1][2][3][4]
This is while in the current j2 template file for Filebeat on the manager node (https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-filebeat/templates/filebeat.yml.j2) line: 61, we are using the "TLS" option instead.

I couldn't find any documentation for the current version about this option (TLS) on the elastic.co website. However, there is an outdated document about that [5].

BTW, the problem occurs in a distributed architecture, when you set up SSL on logstash on the ELK server and specify the "filebeat_ssl_key_file" and "filebeat_ssl_certificate_file" arguments for that. In such a case, the triggered condition in filebeat.yml.j2 file at line 59:

`{% if filebeat_ssl_certificate_file and filebeat_ssl_key_file %}`

will cause the "tls:" in line 61 become present in the final config file. 

The problem is if you set up SSL/TLS on the logstash (on the ELK server), it would not understand filebeat speaking to him (error: wrong protocol version or sth). but when you change the TLS into SSL (in the filebeat configuration), and change the "certificate_key: " into "key: ", and add the appropriate "certificate_authorities" section, everything works fine.

edited: the exact error on the logstash.plain:

> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191] Caused by: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER

error on filebeat:
> ERROR	logstash/async.go:256	Failed to publish events caused by: client is not connected

Have already traced the SSL handshake using tcpdum on logstash, it doesn't complete.

Moreover, if you are using a separate CA file (to use your own signing server), you should use "certificate_authorities: " section in the filebeat config file. This section is not automatically generated. and is commented out in the template file (with a hardcoded value of "/etc/pki/root/ca.pem"). This is while the other ssl/tls related options are configured properly using j2 variables (eg. "certificate: ", "certificate_key: ").

Many thanks ;o)
---
References:
[1]: Secure communication with Elasticsearch: https://www.elastic.co/guide/en/beats/filebeat/current/securing-communication-elasticsearch.html
[2]: Secure communication with Logstash using ssl: https://www.elastic.co/guide/en/beats/filebeat/current/configuring-ssl-logstash.html
[3]: Specify SSL settings: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html
[4]: Logstash Beats input plugin: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html
[5]: Filebeat Version 1.3 TLS options: https://www.elastic.co/guide/en/beats/filebeat/1.3/configuration-output-tls.html

**Comment by manuasir** [comment]
Hello @M-Golyani ,

Thank you for reporting this. We will evaluate the implementation. If it is decided so, it will be added to the roadmap as a new feature that will be done for the next upcoming releases. Additionally, with the adaptation to Elastic 7, the Logstash component will be completely removed, a determining factor to take into account.

Best regards

**Comment by jm404** [comment]
Hi @M-Golyani,

We implemented different options to make users able to deploy Filebeat, Elasticsearch and Kibana with XPack enabled and autogenerate and distribute the required certificates, please check https://github.com/wazuh/wazuh-ansible/blob/master/playbooks/wazuh-elastic_stack-distributed.yml for some examples

I'm closing this issue as it's already implemented, please feel free to open a new one if you need it.

Best regards,

Jose
