### ISSUE TITLE
Different default connection protocol between Agent and Manager

### ISSUE THREAD

**Issue by M-Golyani** [wazuh/wazuh-ansible#181]
Hi there :)

In the default YAML configuration file for the agent (when installing them using ansible), the default protocol to use to connect to the manager is set as "TCP", while in the default YAML configuration file for the manager, the default connection protocol is set as "UDP". 
This causes the default playbooks to not work.

Ansible configuration file for Agents:
[agent's defaults/main.yml](https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-agent/defaults/main.yml#L5) line 5:

`---`
`wazuh_managers:`
`  - address: 127.0.0.1`
`    port: 1514`
**_`    protocol: tcp`_**
`    api_port: 55000`
`    api_proto: 'http'`
`    api_user: null`
`wazuh_profile: null`
`...`
`...`
`...`

Ansible configuration file for Manager:
[manager's defaults/main.yml](https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-manager/defaults/main.yml#L43) line 43:

`...`
`...`
`...`
`  connection:`
`    - type: 'secure'`
`      port: '1514'`
**_`      protocol: 'udp'`_**
`      queue_size: 131072`
`...`
`...`
`...`

Thanks ;)

**Comment by manuasir** [comment]
Hello @M-Golyani ,

Thanks for reporting this. We will check this out and fix it as soon as possible.

Regards

**Comment by manuasir** [comment]
Done here #204 
Thanks @M-Golyani , as always, for your amazing collaboration to this repository. Your help is always much appreciated.

Best regards
