### ISSUE TITLE
OpenDistro Elasticsearch and Kibana instead of elastic co

### ISSUE THREAD

**Issue by L1ghtn1ng** [wazuh/wazuh-ansible#185]
Would be good if part of the documentation and the playbook/galaxy role was to move to

https://opendistro.github.io/for-elasticsearch/downloads.html

As it has features that would be good to have like being able to login to kibana by default

**Comment by jm404** [comment]
Hi @L1ghtn1ng ! 

I've reviewed OpenDistro and their features look great, we will test it and will let you know when we add support for it. 

Thank you for contributing!

Best Regards,

Jose

**Comment by L1ghtn1ng** [comment]
Thanks Jose
________________________________

**Comment by manuasir** [comment]
Done here https://github.com/wazuh/wazuh-ansible/pull/417. This will be probably shipped with the upcoming release.

Thank you @L1ghtn1ng !
