### ISSUE TITLE
`elasticsearch` and `logstash` roles: condition and parameters to install java

### ISSUE THREAD

**Issue by ouadi** [wazuh/wazuh-ansible#19]
The JRE is being installed automatically by `elasticsearch` and `logstash` roles.

Is there a plan to review these two roles to behave like `wazuh_agent` and `wazuh_manager` roles as far as java install is concerned? These two roles use the condition `wazuh_xxx_config.cis_cat.install_java` to install Java and both of them installs the OpenJDK JRE instead of Oracle JRE.

**Comment by jlruizmlg** [comment]
@ouadi than's for your feedback, we can do it, keep like optional, is not a bad idea! thanks!

**Comment by ouadi** [comment]
Do you need help? Will you accept a PR in this regards? I have already implement it in a fork and it will a pleasure to share my implementation (the good spirit of open source community :-) ).

**Comment by mjflve** [comment]
Hi @ouadi,

Sure, please feel free to submit your PR, we appreciate the help, thanks!

Best regards,

**Comment by ouadi** [comment]
PR submitted.
