### ISSUE TITLE
wazuh-manager invalid default value for ssl_manager_cert & key

### ISSUE THREAD

**Issue by M-Golyani** [wazuh/wazuh-ansible#193]
Hi there :)

In wazuh-manager role, here: https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-manager/defaults/main.yml#L55
the default value of ssl_manager_cert & ssl_manager_key is set to the respective file under /var/ossec/etc/ :
`ssl_manager_cert: '/var/ossec/etc/sslmanager.cert'`
`ssl_manager_key: '/var/ossec/etc/sslmanager.key'`

These two variables are used in tasks/main.yml, and templates/var-ossec-etc-ossec-server.conf.j2
and in the last cases, only the "basename" is used. However, in the first case (https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-manager/tasks/main.yml#L51), we have:
`- name: Copy CA, SSL key and cert for authd`
`  copy:`
`    src: "{{ item }}"`
`    dest: "/var/ossec/etc/{{ item | basename }}"`
`    mode: 0644`
`  with_items:`
`    - "{{ wazuh_manager_config.authd.ssl_agent_ca }}"`
`    - "{{ wazuh_manager_config.authd.ssl_manager_cert }}"`
`    - "{{ wazuh_manager_config.authd.ssl_manager_key }}"`

which would try to copy the ssl_manager_cert file from "/var/ossec/etc" (which is set in default/main.yml) on the ansible server to its proper destination (src: "{{item}}").
to avoid this, the default value in "defaults/main.yml" should be changed to "sslmanager.cert" & "sslmanager.key" instead of "/var/ossec/etc/sslmanager.cert" , ...

Bests, 
Mohammad.

**Comment by rshad** [comment]
Hi @M-Golyani ,

Sorry about the delayed answer!

Thank you for reporting and for being interested in improving Wazuh services.

I'll look on this issue and will keep you updated.

Kind regards,

Rshad

**Comment by rshad** [comment]
Hi @M-Golyani,

We considered your changes as valid to be implemented, please find below the applied changes:

1. In [`roles/wazuh/ansible-wazuh-manager/defaults/main.yml`](https://github.com/wazuh/wazuh-ansible/blob/cd090d63eb848132df63e6b1a268470a6c842251/roles/wazuh/ansible-wazuh-manager/defaults/main.yml) we removed the complete path set the basename only.

https://github.com/wazuh/wazuh-ansible/blob/cd090d63eb848132df63e6b1a268470a6c842251/roles/wazuh/ansible-wazuh-manager/defaults/main.yml#L57-L58


2. In [`roles/wazuh/ansible-wazuh-manager/tasks/main.yml`](https://github.com/wazuh/wazuh-ansible/blob/cd090d63eb848132df63e6b1a268470a6c842251/roles/wazuh/ansible-wazuh-manager/tasks/main.yml) it does not take the basename as it already has the items as a basename, which will be concatenated with the complete path as indicated below:

https://github.com/wazuh/wazuh-ansible/blob/cd090d63eb848132df63e6b1a268470a6c842251/roles/wazuh/ansible-wazuh-manager/tasks/main.yml#L73

The changes were tested and all the results referred to successful testing.

Changes will be merged into the parent branch [`3.9.5_7.2.1`](https://github.com/wazuh/wazuh-ansible/tree/3.9.5_7.2.1).

Thanks again for your interests in improving Wazuh services!

Kind regards,

Rshad
