### ISSUE TITLE
ClearOS and VyOS Install

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh-ansible#218]
How would I install on a ClearOS (CentOS derivative) or VyOS (Debian derivative) without manually changing the wazuh-agent role and tasks?  I've tested on a ClearOS machine and the playbook recognizes the OS as Debian and then obviously throws errors.

**Comment by jm404** [comment]
Hi @alphaDev23,

We have not tested the OS's that you mentioned. We will evaluate this to determine if several changes are required or just some tweaks since they are based on currently supported systems (CentOS and Debian)

Thank you for your feedback, it's really appreciated

Best regards,

Jose

**Comment by alphaDev23** [comment]
The above should install without issue once the OS is correctly recognized.

**Comment by xr09** [comment]
Hi @alphaDev23 

Those two distros you mention are very specific, ClearOS for example has an app market for creating specific services (in several places they use it as a FOSS replacemente for Active Directory), an VyOS is more network oriented. What I mean is these distros are not created with the purpose of deploying custom services like on Debian/Ubuntu/CentOS.

Also the fact that ClearOS is being recognized as Debian is more of an issue with Ansible OS detection than this playbook itself.

I'm closing this one but please feel free to open another issue if considered necessary.
