### ISSUE TITLE
 Amazon Linux 2 conditions are wrong?

### ISSUE THREAD

**Issue by NPoi** [wazuh/wazuh-ansible#244]
Hello team, 

When I tried to install Wazuh-manager on Amazon Linux 2, certain tasks were skipped.
I think this is the wrong condition, but what about it?

Since it is a conditional expression when the value of "ansible_distribution_major_version" is NA, it seems to be skipped in Amazon Linux 2 where this value is "2".

```
$ ansible -m setup -i /etc/ansible/hosts manager | grep distribution
        "ansible_distribution": "Amazon",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/system-release",
        "ansible_distribution_file_variety": "Amazon",
        "ansible_distribution_major_version": "2",
        "ansible_distribution_release": "NA",
        "ansible_distribution_version": "2",
```

https://github.com/wazuh/wazuh-ansible/blob/c7c15f614c6fa09816c7b55945e62fb6d0cb9b85/roles/wazuh/ansible-wazuh-manager/tasks/RedHat.yml#L30

https://github.com/wazuh/wazuh-ansible/blob/c7c15f614c6fa09816c7b55945e62fb6d0cb9b85/roles/wazuh/ansible-wazuh-manager/tasks/RedHat.yml#L39

https://github.com/wazuh/wazuh-ansible/blob/c7c15f614c6fa09816c7b55945e62fb6d0cb9b85/roles/wazuh/ansible-wazuh-manager/tasks/RedHat.yml#L50

https://github.com/wazuh/wazuh-ansible/blob/c7c15f614c6fa09816c7b55945e62fb6d0cb9b85/roles/wazuh/ansible-wazuh-manager/tasks/RedHat.yml#L71

Isn't `ansible_distribution_major_version ==" NA "`, not `ansible_distribution_release ==" NA "`?

Regards,

Daisuke.

**Comment by jm404** [comment]
Hi @NPoi ,

I changed this because recently checked the facts and obtained the `ansible_distribution_release==NA` in Ansible 2.5

Which Ansible version are you running? It seems like newer Ansible version properly grabs the major version like the outpout shown in your post.

We will review it in different Ansible versions to verify the consistency of the facts of the Amazon Linux distributions

Best regards

Jose

**Comment by jm404** [comment]
Hi @NPoi ,

Sorry for the late response, we are using ansible 2.8+ without issues at the moment, please let us know if you keep facing errors with this issue.

Best regards,

Jose

**Comment by NPoi** [comment]
Hi @jm404,

Thank you for your reply.
I'll try it on my end as well. 

If you're already running on 2.8+, I think you'll be fine, so I'll close this issue.

Best regards,

Daisuke
