### ISSUE TITLE
min server requirements?

### ISSUE THREAD

**Issue by niccolox** [wazuh/wazuh-ansible#278]
what's the min server requirements for this Ansible role? 

4gb? 2gb? 
how does this get split between Elasticsearch, Wazuh? etc

**Comment by manuasir** [comment]
Hello @niccolox ,

It depends on how many components are you planning to deploy.  For a lab or test environment, and as orientation, you can take into account these hardware requirements:
- Single host environment: 4 GB / 2 core.
- Wazuh manager: 1GB / 2 core.
- Wazuh agent: 512MB / 1 core.
- Elasticsearch: 4GB / 2 core.
- Kibana: 4GB / 2 core.

Let me know if that helps
Regards

**Comment by niccolox** [comment]
Hi
Does single host include all components?

**Comment by jm404** [comment]
Hi @niccolox,

The single hosts includes the Wazuh Manager + Filebeat + Elasticsearch + Kibana

Sorry for the late response,

Feel free to open a new issue if you have any other questions. Also, you can check our [Community Slack] (https://wazuh.com/community/join-us-on-slack/)!

Best regards,

Jose
