### ISSUE TITLE
Add timeout on yum install

### ISSUE THREAD

**Issue by gmarziou** [wazuh/wazuh-ansible#29]
Hello,

On CentOS, I have run into `yum install wazuh-agent` taking forever because it was waiting for `yum.lock`  held by another process. This was also causing ssh disconnections with ansible yum zombie processes on the host.

I think the role would be more robust by using `async` and `poll`:

~~~yaml
- name: Linux | Install wazuh-agent
  package: name=wazuh-agent state=latest
  async: 60
  poll: 10
  tags:
    - init
~~~

With these settings, when yum does not complete within 60 seconds, the playbook fails as below:

~~~
TASK [ansible-wazuh-agent : Linux | Install wazuh-agent] *******************
                                                                            
fatal: [ps-majlnx.example.local]: FAILED! => {                             
    "changed": false                                                        
}                                                                           
                                                                            
MSG:                                                                        
                                                                            
async task did not complete within the requested time 
~~~ 

Maybe with a variable for timeout value. I can submit a PR if agreed.

**Comment by mjflve** [comment]
Hi @gmarziou,

Sorry for the late reply, please feel free to submit a PR with this proposal, Thanks!

Best Regards,
