### ISSUE TITLE
Java RPM in elasticsearch RedHat.yml is invalid

### ISSUE THREAD

**Issue by Mattz0r** [wazuh/wazuh-ansible#30]
Hello,

Just attempted to install this, however was getting an error when trying to install Java, got a 404.

Edited the file:

wazuh-ansible/ansible-role-elasticsearch/tasks/RedHat.yml

Changed the URL to:  http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jre-8u171-linux-x64.rpm

Then re-ran the playbook, this allowed Java to be installed.

**Comment by jlruizmlg** [comment]
Hi @Mattz0r the URL has been fixed in the following commit: 2f33b7252df9c1a22fa2ac3022cccb8473e17194, thanks for report this issue!
