### ISSUE TITLE
New API configuration behavior on 3.11

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-ansible#339]
### Description

Starting with `v3.11` the Wazuh plugin for  Kibana has a new behavior when upgrading. 

Documented here: https://github.com/wazuh/wazuh-kibana-app/issues/1465

The former `config.yml` got renamed to `wazuh.yml`, which brought some internal changes as well, the API settings will no longer be stored in the Elastic index named `.wazuh`, these settings got migrated to `wazuh.yml`.

The new behavior is like this:

- The first time booting `3.11` Wazuh plugin detects if there's an `.wazuh` index and moves it to `wazuh.yml`, this info gets deleted from Elastic.

- On the following restart cycles there will be no `.wazuh` index

### Proposed workflow

Following Ansible's declarative nature we propose to always delete the `.wazuh` index if exists and write API settings to `wazuh.yml`. In the case the user updated the password, then the playbook will override it in both the API and Kibana settings.

### Tasks

The following scenarios should be tested:

- [x] New deployment
- [x] Upgrading from `3.10` to `3.11` (no other changes)
- [x] Upgrading from `3.10` to `3.11` (changing API settings)

**Comment by jm404** [comment]
Done in #342
