### ISSUE TITLE
Add wazuh-agent /var/ossec/etc/internal_options.conf template

### ISSUE THREAD

**Issue by maxverro** [wazuh/wazuh-ansible#34]
In order to use centralized configuration it would be nice to have a template for the internal_options.conf file. 

To use centralized configuration this is a requirement. From the doc:

> When setting up remote commands in the shared agent configuration, you must enable remote commands for Agent Modules. This is enabled by adding the following line to the file etc/local_internal_options.conf in the agent:

`wazuh_command.remote_commands=1`

This would allow to set the logcollector.remote_commands value. With this value set to 1 we could configure the centralized configuration during the installation process.

For additional information see the doc
https://documentation.wazuh.com/3.x/user-manual/reference/internal-options.html?highlight=logcollector%20remote_commands#logcollector
https://documentation.wazuh.com/3.x/user-manual/reference/centralized-configuration.html?highlight=centralized%20configuration

**Comment by jlruizmlg** [comment]
Hi @MaxVerro you are right, but with a little modification, we never should have a template for "internal_optins.conf" file, if we want to modify any parameter from interal_options we should add to the file local_internal_options.conf the parameter with the configuration.

The file internal_options.conf is replaced in each upgraded with new content. If we want to change values from this file is recommended to use local_internal_options.conf

We will upgrade to use local_internal_options.conf, thanks for the feedback!
