### ISSUE TITLE
Protocol mismatch between agent and manager default playbooks

### ISSUE THREAD

**Issue by kadafax** [wazuh/wazuh-ansible#346]
Just a small issue with the default playbooks for the agent and the manager:
The agent is configured to use tcp/1514 [1] and the manager will listen on udp/1514 [2].
[1]:
https://github.com/wazuh/wazuh-ansible/blob/5aa0f2e6c42af9c155706a523a4c8570e9aa5e26/playbooks/wazuh-agent.yml#L9
[2]: 
https://github.com/wazuh/wazuh-ansible/blob/5aa0f2e6c42af9c155706a523a4c8570e9aa5e26/roles/wazuh/ansible-wazuh-manager/defaults/main.yml#L90

**Comment by jm404** [comment]
Hi @kadafax,

I opened a PR to fix this https://github.com/wazuh/wazuh-ansible/pull/347, will be merged as soon as the tests finish.

Thanks for reporting this!

Best regards,

Jose
