### ISSUE TITLE
Deploying agent fail on Centos 8 because of malformed xml in /var/ossec/etc/ossec.conf

### ISSUE THREAD

**Issue by kadafax** [wazuh/wazuh-ansible#353]
Hi there,

Small issue:
Because Centos-8 is not -yet- fully supported in the templates, using wazuh-agent.yml playbook on this version will result in an incorrectly formatted /var/ossec/etc/ossec.conf file:

```
  <wodle name="open-scap">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>
        <profile>xccdf_org.ssgproject.content_profile_pci-dss</profile>
        <profile>xccdf_org.ssgproject.content_profile_common</profile>
      </content>
  </wodle>
```

Notice the \</content\> who is never open before because ansible_distribution_major_version is no yet tested for '8'.

https://github.com/wazuh/wazuh-ansible/blob/5aa0f2e6c42af9c155706a523a4c8570e9aa5e26/roles/wazuh/ansible-wazuh-agent/templates/var-ossec-etc-ossec-agent.conf.j2#L94

**Comment by xr09** [comment]
Hi @kadafax , thanks for reporting this, I fixed this template on the manager but totally missed the agent's.

As you can see [here](https://github.com/wazuh/wazuh-ansible/commit/6eebfa4f2c83320c414ab33815b8ab3ef5a284cb#diff-32fe8944da2693b2f5530b3810a9669a) this openscap policy is not yet available for CentOS 8 so we leave this blank.
