### ISSUE TITLE
Adding Wazuh group during Agent registration

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-ansible#359]
Hi team,

Agent-authd has the capability to assign agents groups during the agent registration using the option
`-G group1,group2,group3`. (https://documentation.wazuh.com/3.11/user-manual/reference/tools/agent-auth.html)

But our Wazuh-agent playbook does not include an option to add the groups during the agent registration: 
https://github.com/wazuh/wazuh-ansible/blob/2375dedfb8da3e7d77721e0fc1ecc9d7f5e129f2/roles/wazuh/ansible-wazuh-agent/defaults/main.yml#L36-L43

It is not a common scenario to manage agents using both Ansible and Groups, but it would be a nice and simple feature to have.

Best regards,
Miguel

**Comment by xr09** [comment]
Hello Miguel,

Definitely this looks like a nice feature to support. We'll take into consideration and may ship it in the near future.

Thanks for reporting!

**Comment by rshad** [comment]
Working branch: [feature-359-agent-auth-groups](https://github.com/wazuh/wazuh-ansible/tree/feature-359-agent-auth-groups).

**Comment by rshad** [comment]
Hi!

A first-thought configuration would be to add the following config.:

- [ ] A list of groups `Empty by default`.
- [ ] A task to create the defined groups `wazuh-manager role`.
- [ ] A task to register the agent with the defined groups `wazuh-agent role`.

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

The required changes have been added and verified.

#### Configuration Description

- **wazuh-manager role**

We firstly defined a new variable in the manager's role variables to define the list of groups to create.

https://github.com/wazuh/wazuh-ansible/blob/50ad3e07da8f4cf8b4c1afb3a6c52b19f83cb60d/roles/wazuh/ansible-wazuh-manager/defaults/main.yml#L401-L402

https://github.com/wazuh/wazuh-ansible/blob/50ad3e07da8f4cf8b4c1afb3a6c52b19f83cb60d/roles/wazuh/ansible-wazuh-manager/tasks/main.yml#L358-L363
On the following, we have the log of both cases, registering the agent adding it to 1 group and adding it to multiple groups.

- **wazuh-agent role**

Once the groups are created by the manager, we then would be able to add the agent to 1 or more groups when registering it. To do so we first added a new variable which represents the list of groups to which the agent will be added.

https://github.com/wazuh/wazuh-ansible/blob/50ad3e07da8f4cf8b4c1afb3a6c52b19f83cb60d/roles/wazuh/ansible-wazuh-agent/defaults/main.yml#L36-L40

And also added the corresponding changes to add it to the groups.

```yaml
    - name: Linux | Register agent (via authd)
      shell: >
        /var/ossec/bin/agent-auth
.
.
.
        {% if wazuh_agent_authd.groups is defined and wazuh_agent_authd.groups != None %}
        -G "{{ wazuh_agent_authd.groups | join(',') }}"
        {% endif %}
      register: agent_auth_output
.
.
.
```

**Log: 1-group case**
```shell
root@manager-bionic:/var/ossec# ./bin/agent_groups -l
Groups (2):
  default (0)
  group2 (1)
Unassigned agents: 0.


root@manager-bionic:/var/ossec# ./bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: manager-bionic (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: agent-bionic, IP: 172.18.0.3, Active

List of agentless devices:

root@manager-bionic:/var/ossec#


root@manager-bionic:/var/ossec# /var/ossec/bin/agent_groups -l -g group2
1 agent(s) in group 'group2':
  ID: 001  Name: agent-bionic.
root@manager-bionic:/var/ossec#


    TASK [wazuh/ansible-wazuh-manager : Create agent groups] ***********************
    changed: [manager-bionic] => (item=group2)

    TASK [wazuh/ansible-wazuh-agent : Linux | Register agent (via authd)] **********
    changed: [agent-bionic]
```

#### Testing Scenarios

We verified the changes on Ubuntu Bionic:18.04, simulating the following cases:
**Success Expected**
- An empty list of groups in both `wazuh-manager` and `wazuh-agent` ✔️ 
- 1-group list in `wazuh-manager` and add the agent to it. ✔️ 
- [2-3]-group list in `wazuh-manager` and add the agent to them. ✔️ 

**Failure Expected**
- Tried to add the agent to non-created  group. ❌ 

Kr,

Rshad

**Comment by rshad** [comment]
**Log: 1-group case**
```shell
root@manager-bionic:/var/ossec# ./bin/agent_groups -l
Groups (2):
  default (0)
  group2 (1)
Unassigned agents: 0.


root@manager-bionic:/var/ossec# ./bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: manager-bionic (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: agent-bionic, IP: 172.18.0.3, Active

List of agentless devices:

root@manager-bionic:/var/ossec#


root@manager-bionic:/var/ossec# /var/ossec/bin/agent_groups -l -g group2
1 agent(s) in group 'group2':
  ID: 001  Name: agent-bionic.
root@manager-bionic:/var/ossec#


    TASK [wazuh/ansible-wazuh-manager : Create agent groups] ***********************
    changed: [manager-bionic] => (item=group2)

    TASK [wazuh/ansible-wazuh-agent : Linux | Register agent (via authd)] **********
    changed: [agent-bionic]
```

**Log: 3-group case**
```
root@manager-bionic:/var/ossec# ./bin/agent_groups -l
Groups (4):
  default (0)
  group3 (1)
  group4 (1)
  group5 (1)
Unassigned agents: 0.


root@manager-bionic:/var/ossec# ./bin/agent_groups -l
Groups (4):
  default (0)
  group3 (1)
  group4 (1)
  group5 (1)
Unassigned agents: 0.
root@manager-bionic:/var/ossec# /var/ossec/bin/agent_groups -l -g group3
1 agent(s) in group 'group3':
  ID: 001  Name: agent-bionic.
root@manager-bionic:/var/ossec# /var/ossec/bin/agent_groups -l -g group4
1 agent(s) in group 'group4':
  ID: 001  Name: agent-bionic.
root@manager-bionic:/var/ossec# /var/ossec/bin/agent_groups -l -g group5
1 agent(s) in group 'group5':
  ID: 001  Name: agent-bionic.
```

**Comment by rshad** [comment]
Hi all!

We added the tag: `molecule-idempotence-notest` for the following task, to ignore the `idempotence` test.
``` yml
- name: Create agent groups
  command: "/var/ossec/bin/agent_groups -a -g {{ item }} -q"
  with_items:
    - "{{ agent_groups.groups }}"
  when:
    - ( agent_groups.groups is defined) and ( agent_groups.groups|length > 0)
  tags: molecule-idempotence-notest
```

Kr,

Rshad

**Comment by rshad** [comment]
Changes Approved and Merged. #361 .
