### ISSUE TITLE
Install agents with ansible, different servers and systems

### ISSUE THREAD

**Issue by fconcha** [wazuh/wazuh-ansible#36]
A question,
can I do an agent installation on solaris machines ?, using ansible

could you guide me in some way to install agents on servers, firewall or systems that do not have an already defined role, using ansible.

Regards
Felipe

**Comment by fconcha** [comment]
Hello everyone
do you have any suggestions :)

**Comment by jlruizmlg** [comment]
@fconcha please look the branch solaris: https://github.com/wazuh/wazuh-ansible/tree/solaris

**Comment by cadoming** [comment]
Hi @fconcha,

Did you get the agent installed on solaris? If you have any other question at any time.

**Comment by fconcha** [comment]
Thanks finally I could do it.
I did it this way


________________________________


- hosts: solaris
  vars:
    template:
      ip: “192.168.2.2"

  tasks:
  - name: descarga de solaris
    get_url:
      url: https://packages.wazuh.com/3.x/solaris/i386/11/wazuh-agent_v3.3.1-sol11-i386.p5p
      dest: /tmp

  - name: Instalar solaris de solaris
    shell: yes all |pkg install -g wazuh-agent_v3.3.1-sol11-i386.p5p wazuh-agent
    args:
      chdir: /tmp

  - name: Setting manager IP in agent
    lineinfile:
      path: /var/ossec/etc/ossec.conf
      regexp: "<address>MANAGER_IP</address>"
      line: "<address>{{ template.ip }}</address>"

  - name: registro del agent via ossec
    command: "/var/ossec/bin/agent-auth -m {{ template.ip }}"

  - name: Reinicio del agente
    command: "/var/ossec/bin/ossec-control restart"

  - name: eliminar paquete de instalacion solaris
    command: "rm /tmp/wazuh-agent_v3.3.1-sol11-i386.p5p"
______________________________________________________________________


Ejecutar el playbook

# ansible-playbook solaris.yml


Regards
Felipe

**Comment by cadoming** [comment]
Hi @fconcha,  

We are glad that you have done the installation, for any other question we will be happy to answer you.
