### ISSUE TITLE
Permissions for Filebeat certs

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-ansible#373]
Hi team,

I noticed that the permissions for Filebeat cert and key are 0644.

https://github.com/wazuh/wazuh-ansible/blob/e1270cde5bd9997dc62ace88bd2713b9f1bd2e8f/roles/wazuh/ansible-filebeat/tasks/config.yml#L29-L39

Having Filebeat key with read permission for all the users is not required, and could be a potential threat.

**Comment by jm404** [comment]
Hi @migruiz4,

Thanks for reporting this, we will open a PR soon to fix it.

Best regards,

Jose

**Comment by jm404** [comment]
I've diagnosed some permissions are too open and should be updated so it will require a whole review of the permissions in every role filtering by `mode` keyword.

Best regards,

Jose

**Comment by jm404** [comment]
Done in #382
