### ISSUE TITLE
Default Port config 1514 TCP/UDP incongruent between manager and agent

### ISSUE THREAD

**Issue by Ilikeskeletons** [wazuh/wazuh-ansible#378]
Not sure wether this is working as intended:

When running the Ansible playbooks with default settings aside from the necessary changes such as ip addresses etc, the agent will be configured to use port 1514 TCP, while the manager is configured to use port 1514 UDP. The agent is properly registered in Wazuh manager, but shows up as "never connected" and will throw errors that its connection to the manager was refused.

Changing the port to 1514 UDP in the wazuh-agent.yml resolves this issue and the agent's status changes to active in the Wazuh manager.

 wazuh-ansible/playbooks/wazuh-agent.yml 

    wazuh_managers:
      - address: <your manager IP>
        port: 1514
        protocol: tcp

 wazuh-ansible/roles/wazuh/ansible-wazuh-manager/defaults/main.yml 

  connection:
    - type: 'secure'
      port: '1514'
      protocol: 'udp'

wazuh-ansible/roles/wazuh/ansible-wazuh-agent/defaults/main.yml 

wazuh_managers:
  - address: 127.0.0.1
    port: 1514
    protocol: udp

**Comment by jm404** [comment]
Hi @Ilikeskeletons ,

This has been already fixed(https://github.com/wazuh/wazuh-ansible/blob/devel/playbooks/wazuh-agent.yml) and will be merged in our next release, please check our `devel` branch for the latest updates.

I'm closing this issue, please feel free to open a new one if you need.

Thanks for your feedback, it's really appreciated.

Best regards,

Jose
