### ISSUE TITLE
Update wazuh-ansible regarding 3.12 wazuh-kibana-app changes

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-ansible#387]
## Objective

The next release for Wazuh Kibana app related to Wazuh v3.12 includes relevant changes (permissions, different files locations) and we should visit and transfer this to our ansible tools.

I.e: The `wazuh.yml` file is now located on `/usr/share/kibana/optimize/wazuh/config/wazuh.yml`

## Tasks
- [x] File arrangement check
- [x] Permissions status check

**Comment by xr09** [comment]
It was required to create the directory `/usr/share/kibana/optimize/wazuh/config` after the plugin installation since the plugin itself doesn't take care of this.

**Comment by jm404** [comment]
Hi @xr09,

As it`s under `/optimize` folder, it will be probably created in the optimization phase of Kibana, please evaluate if we should move the credentials configuration tasks after the optimization process.

Best regards,

Jose
