### ISSUE TITLE
Support all remote connection options.

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh-ansible#41]
The existing [template](https://github.com/wazuh/wazuh-ansible/blob/master/ansible-wazuh-manager/templates/var-ossec-etc-ossec-server.conf.j2#L118) only supports a subset of the [remote](https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/remote.html) options.

For instance, the `syslog` connection type should have an [allowed_ips](https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/remote.html#allowed-ips) option, according to the docs:
> It is necessary to list at least one IP address when using the syslog connection type.

**Comment by jlruizmlg** [comment]
Merged in the pull request #40
