### ISSUE TITLE
Documentation: Open Distro deployment

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-ansible#420]
Hello,

This issue tracks the documentation process for the Ansible deployment for Wazuh + Open Distro.

- [x] Redact README.
- [x] Show playbooks examples.
- [ ] Cover different use cases.
- [x] Describe new variables.
- [x] Include section in the Wazuh documentation. [Related wazuh-documentation PR](https://github.com/wazuh/wazuh-documentation/pull/3009)
  
Regards

**Comment by Zenidd** [comment]
### Status Oct 7, 2020

#### Show playbooks example task:

I've been working on a production-ready template including the Wazuh cluster, ODFE cluster and Kibana node. It also includes a related inventory file where users should enter their instances addresses. It is almost ready but it still needs a full deploy test along with replacing the test addresses with placeholders.
  
I'm going to continue with a single node environment template and both examples will be included and explained on the `README.md`.

#### Update wazuh-documentation task:

For this task, I'm including the ODFE roles in the related `wazuh-ansible `documentation section. The variables reference section will be updated with the ODFE roles variables along with an update for the already existing roles. [Related PR](https://github.com/wazuh/wazuh-documentation/pull/3009)


Greetings,

JP
