### ISSUE TITLE
Support all localfile options.

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh-ansible#43]
The existing [template](https://github.com/wazuh/wazuh-ansible/blob/master/ansible-wazuh-manager/templates/var-ossec-etc-ossec-server.conf.j2#L325) only supports [localfile](https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/localfile.html) options `log_format`, `command`, `frequency` and `location`.  It should also support `only_future_events`, `query`, `label`, `target`, and `out_format`.

**Comment by jlruizmlg** [comment]
Merged in the pull request #40
