### ISSUE TITLE
Allow rule exclusions

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh-ansible#44]
The existing [ossec.conf template](https://github.com/wazuh/wazuh-ansible/blob/master/ansible-wazuh-manager/templates/var-ossec-etc-ossec-server.conf.j2#L297) hardcodes exclusion of the [`0215-policy_rules.xml`](https://github.com/wazuh/wazuh/blob/master/etc/rules/0215-policy_rules.xml) rules file.

It should be possible to exclude other rules, or to include the above-named rule.

**Comment by jlruizmlg** [comment]
Merged in the pull request #40
