### ISSUE TITLE
merged PR #426 is not available in master or in latest release

### ISSUE THREAD

**Issue by pescobar** [wazuh/wazuh-ansible#450]
Hi,

While upgrading our wazuh installation to the latest version using ansible we have noticed that PR https://github.com/wazuh/wazuh-ansible/pull/426 was merged but is not available in the latest release https://github.com/wazuh/wazuh-ansible/releases/tag/v3.13.1_7.8.0 or in master. I cannot find variable `kibana_ssl_verification_mode` in https://github.com/wazuh/wazuh-ansible/blob/master/roles/elastic-stack/ansible-kibana/templates/kibana.yml.j2

**Comment by xr09** [comment]
Hi @pescobar  I see that PR was merged into another branch, not `devel` as usual.

The branch is  [pr-426-kibana_extra_ssl_option](https://github.com/wazuh/wazuh-ansible/tree/pr-426-kibana_extra_ssl_option)

I rebased devel into it and opened a new PR here: https://github.com/wazuh/wazuh-ansible/pull/451

Thanks for the heads up!

**Comment by xr09** [comment]
Hey @pescobar,

#451 was merged into `devel`, this will be available in our next release.

Closing this issue, thanks for the contribution!
