### ISSUE TITLE
Add support to create Wazuh-API users on wazuh-manager role

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-ansible#457]
Hi team,

- The new Wazuh 4.0 API changes the way new API users are created: In the previous Wazuh versions, the new users were generated by placing the desired credentials on `/var/ossec/api/configuration/auth/user`. 

- In Wazuh 4.0 these users should be generated using the `Create new user - /security/users` endpoint. Also, the users have a policy attached containing their permission scope.

![image](https://user-images.githubusercontent.com/14923294/91050011-56ecfa80-e61e-11ea-8791-b2f0dfa97c8d.png)

- We should support the creation of new users and assign them an already existing role. Tagging the related tasks with a proper tag could be really useful to allow launching the role just to create new users.

Greetings,

JP

**Comment by xr09** [comment]
This was fixed by https://github.com/wazuh/wazuh-ansible/pull/458
