### ISSUE TITLE
Vuls woodle configuration is Depricated

### ISSUE THREAD

**Issue by esfateev** [wazuh/wazuh-ansible#464]
Hi Team!
It seems like Vuls integration depricated (https://documentation.wazuh.com/3.3/user-manual/capabilities/vuls.html), but I found vuls woodle configuration in https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-manager/tasks/main.yml

Could you please clean up ansible scripts? Delete this woodle integration?

Thanks!
BR, Eugene Fateev

**Comment by xr09** [comment]
Hi @esfateev!

Thanks for pointing this out, looks like this task is due for cleaning since a few releases.

**Comment by manuasir** [comment]
Done here #469 thanks @esfateev
