### ISSUE TITLE
"Babel could not write cache to file: /usr/share/kibana/optimize/.babel_register_cache.json \ndue to a permission issue.

### ISSUE THREAD

**Issue by artem-tomyuk** [wazuh/wazuh-ansible#466]
Hi, getting error:

TASK [elastic-stack/ansible-kibana : Install Wazuh Plugin (can take a while)] ****************************************************************************************************************
[WARNING]: Unable to use /home/kibana/.ansible/tmp as temporary directory, failing back to system: [Errno 13] Permission denied: '/home/kibana'
fatal: [18.156.77.190]: FAILED! => {"changed": true, "cmd": "NODE_OPTIONS=\"--no-warnings --max-old-space-size=2048 --max-http-header-size=65536\" /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.13.2_7.9.1.zip", "delta": "0:00:01.095174", "end": "2020-09-30 16:27:02.808959", "msg": "non-zero return code", "rc": 70, "start": "2020-09-30 16:27:01.713785", "stderr": "Babel could not write cache to file: /usr/share/kibana/optimize/.babel_register_cache.json \ndue to a permission issue. Cache is disabled.\nPlugin installation was unsuccessful due to error \"ENOENT: no such file or directory, mkdir\"", "stderr_lines": ["Babel could not write cache to file: /usr/share/kibana/optimize/.babel_register_cache.json ", "due to a permission issue. Cache is disabled.", "Plugin installation was unsuccessful due to error \"ENOENT: no such file or directory, mkdir\""], "stdout": "", "stdout_lines": []}

workaround: sudo chown -R kibana:kibana /usr/share/kibana

tested on: ami-0a02ee601d742e89f

**Comment by artem-tomyuk** [comment]
fixed with chown -R kibana:kibana /usr/share/kibana

**Comment by Zenidd** [comment]
Hi @artem-tomyuk !

Thanks for pointing this out, seems like we should ensure that the owner and group for ` /usr/share/kibana` and its subdirectories are the right ones. We will review the best solution and include some tasks to fix it as soon as our workflow allows us.

Greetings,

JP
