### ISSUE TITLE
Elasticsearch 7.9.2 fails on start due to jvm.options file

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-ansible#473]
Hi team,

Our elasticsearch role renders the `jvm.options` file when installing elasticsearch. The current wazuh-ansible template has incorrect options for [7.9.2](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/release-notes-7.9.2.html#upgrade-7.9.2) that lead to the hereunder error on elasticsearch start. These errors seem related to the last version of elastic upgrading the bundled JDK to JDK 15. This has been reverted in the last [7.9.3 release](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/release-notes-7.9.3.html#upgrade-7.9.3).

```
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:

error:
Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

[Related thread](https://discuss.elastic.co/t/elasticsearch-wont-start-after-7-9-1-to-7-9-2-upgrade/249878) 

Greetings,
JP

**Comment by neonmei** [comment]
I duplicated the issue by mistake, my bad. 
Here's the issue with the fixing PR for future reference: #500
