### ISSUE TITLE
Update role per java changes on upstream

### ISSUE THREAD

**Issue by neonmei** [wazuh/wazuh-ansible#500]
Hi team!
With upcoming roles release detailed in PR #499, the elastic stack version is bumped to `7.9.3` and there were some changes regarding java version and upstream-distributed `jvm.options` in the versions in between.

 * https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.9.2.html
 * https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.9.3.html

We should reflect those changes on our role, specially because elasticsearch service startup might fail because of this:

```
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly
```

**Comment by Zenidd** [comment]
The new `jvm.options` template looks good and it's really nice that it has different configurations based on java version. The tests are OK so, LGTM!
