### ISSUE TITLE
Errors installing ODFE single node

### ISSUE THREAD

**Issue by sergiogp98** [wazuh/wazuh-ansible#538]
Hi,

I was trying to deploy the [playbook](https://github.com/wazuh/wazuh-ansible/blob/feature-elasticsearch-certs/playbooks/wazuh-odfe-single.yml) but during the installation I run into some issues:

1. **Error looking for unknown certificates** ([task](https://github.com/wazuh/wazuh-ansible/blob/69ba46d11999eb4e3ee31ccf40ccf21ed77924ed/roles/opendistro/opendistro-elasticsearch/tasks/security_actions.yml#L45))

This task copy the certificates in `"{{ local_certs_path }}/certs/{{ item }}"` in `/etc/elasticsearch`. However, the certificates which start with `{{ od_node_name }}` does not match with any local certificates as the following image shows:

![Unknown certificates](https://user-images.githubusercontent.com/26262712/104312658-32af8e80-54d7-11eb-8df7-1ba84f8ce3d1.png)

I could fix it by changing the [instances](https://github.com/wazuh/wazuh-ansible/blob/69ba46d11999eb4e3ee31ccf40ccf21ed77924ed/playbooks/wazuh-odfe-single.yml#L19) with the same [instances name](https://github.com/wazuh/wazuh-ansible/blob/69ba46d11999eb4e3ee31ccf40ccf21ed77924ed/playbooks/wazuh-odfe-single.yml#L20)

![Fix issue](https://user-images.githubusercontent.com/26262712/104313092-d26d1c80-54d7-11eb-8205-20fbdf6a4e3f.png)

2. **Set Elasticsearch and Kibana credentials** ([task](https://github.com/wazuh/wazuh-ansible/blob/69ba46d11999eb4e3ee31ccf40ccf21ed77924ed/roles/opendistro/opendistro-elasticsearch/tasks/main.yml#L59)

This task try to encure that Elasticserch is running and listening the proper port. However, the problem was that I did not notice that the [opendistro_admin_password](https://github.com/wazuh/wazuh-ansible/blob/69ba46d11999eb4e3ee31ccf40ccf21ed77924ed/roles/opendistro/opendistro-elasticsearch/defaults/main.yml#L46) and [opendistro_kibana_password](https://github.com/wazuh/wazuh-ansible/blob/69ba46d11999eb4e3ee31ccf40ccf21ed77924ed/roles/opendistro/opendistro-elasticsearch/defaults/main.yml#L47) where not the same in both `opendistro_elasticsearch` and `opendistro_kibana` roles. This was the error: 

![image](https://user-images.githubusercontent.com/26262712/104315012-98514a00-54da-11eb-847f-323eef0a804f.png)

Also I had problem connecting with Wazuh App since elasticsearch credentials in `filebeat.yml` had not the proper ones.

I think it could be specified somewhere in the documentation that they should be all changed to make a correct installation (in case it is not specified).

I hope this could improve how ansible works.

Regards,
Sergio

**Comment by csabka** [comment]
I had the same issue with multi node install. After I have changed the password opendistro_admin_password  to "admin" it started to work.
A step could be missing which change the password from default one.

**Comment by teddytpc1** [comment]
Hi @sergiogp98.
As we have changed to a new model with Indexer and Dashboard we are not able to reproduce the error. 
@csabka, please let us know if you are still experiencing issues or if you need assistance with an old playbook. Feel free to reopen the issue.
