### ISSUE TITLE
wazuh4.0 - kibana index patterns

### ISSUE THREAD

**Issue by Lakshmi-Ragilla** [wazuh/wazuh-ansible#549]
how to create a hyperlink between the  2 fields in the kibana dashboard and also unable to create an index pattern for it.(URL based links)

**Comment by alberpilot** [comment]
Hello @Lakshmi-Ragilla 

  Can you paste a screenshot about the problem creating the index pattern?
  About creating hyperlink please check: https://www.elastic.co/guide/en/kibana/current/managing-index-patterns.html#scripted-fields
Regards, 
Alberto R
