### ISSUE TITLE
Rename ossec.log to wazuh.log and ossec.json to wazuh.json in Wazuh Ansible

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-ansible#563]
The purpose of this issue is to rename ossec.log to wazuh.log and ossec.json to wazuh.json in Wazuh ansible according to wazuh/wazuh#8086.

**Comment by VictorMorenoJimenez** [comment]
There are no occurrences of `ossec.log` or `ossec.json` in the repository. This issue may be closed.
