### ISSUE TITLE
Clean old code.

### ISSUE THREAD

**Issue by jlruizmlg** [wazuh/wazuh-ansible#57]
The line 

```<directories check_all="yes" realtime="yes" restrict="^C:\wazuh-agent/shared/agent.conf$">C:\wazuh-agent</directories>``` 

is not need it anymore in agents 3.x.

https://github.com/wazuh/wazuh-ansible/blob/master/ansible-wazuh-agent/templates/var-ossec-etc-ossec-agent.conf.j2#L81

**Comment by pillarsdotnet** [comment]
While you're cleaning, any chance of reviewing #51 ?

**Comment by cadoming** [comment]
Hi @jlruizmlg,

This Issue is solved in the PR #86 so Im going to proceed to close it. Thank you @jlruizmlg for your work.

Regards.
Carlos
