### ISSUE TITLE
opendistro-elasticsearch : Add apt repository signing key

### ISSUE THREAD

**Issue by jakko10** [wazuh/wazuh-ansible#605]
OS: Ubuntu 18.04

`fatal: [server]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:GPG error: http://deb.debian.org/debian stretch-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 04EE7237B7D453EC NO_PUBKEY 648ACFD622F3D138, E:The repository 'http://deb.debian.org/debian stretch-backports InRelease' is not signed."}`

![image](https://user-images.githubusercontent.com/49167767/122909585-05a4b900-d35e-11eb-9217-bf5ecb78e012.png)

Looks like there is something fishy going on.

**Comment by teddytpc1** [comment]
Hi jakko,
I need a better understanding of the issue you are facing.
Can you provide the documentation you are using, custom configurations you have made and the command used to execute the playbook?
In addition, I need to know what branch/tag from the wazuh-ansible are you using?

**Comment by jakko10** [comment]
Hi,

I think we can close this ticket because I was not using the correct repo, I was using the 4.3.0 which is no public one as of yet.

**Comment by teddytpc1** [comment]
Ok. Glad to hear you were able to make it work.

**Comment by colans** [comment]
I ran into this one, but didn't know how to reopen it so I created #647.  I have a proposed fix in there too.
