### ISSUE TITLE
Deploying Ansible on Ubuntu 20.04 requires allow_world_readable_tmpfiles or installed ACL package

### ISSUE THREAD

**Issue by HagasSaan** [wazuh/wazuh-ansible#610]
While deploying Wazuh-Manager and Wazuh-Agent via that [instruction](https://documentation.wazuh.com/current/deploying-with-ansible/) playbooks fail with that [error](https://github.com/georchestra/ansible/issues/55#issuecomment-651043423). 

allow_world_readable_tmpfiles setting is risky ([description](https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user)), so please add ACL package installation to Debian/Ubuntu tasks.

Thank you!

**Comment by alberpilot** [comment]
Merged. Thanks a lot for your contribution!
