### ISSUE TITLE
MD5 for windows installer seems to be wrong

### ISSUE THREAD

**Issue by mrfito** [wazuh/wazuh-ansible#613]
I just download the stable repo. 
The wazuh-ansible\roles\wazuh\ansible-wazuh-agent\defaults\main.yml file has this MD5 
md5: 8ffa75d13280f1aa6ffca54f4273df4d

but when I run the playbook, the playbook breaks saying the MD5 is incorrect. The file the playbook downloaded has this MD5 50455229db051712fef18eb7cda1ce65

**Comment by c-bordon** [comment]
Hello Mrfito, thanks for your comment, we have already made the correction in the stable branch, if you see any problem, do not hesitate to open another issue
PR: https://github.com/wazuh/wazuh-ansible/pull/617
