### ISSUE TITLE
Wazuh-agent install not working

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh-ansible#64]
Set up per https://documentation.wazuh.com/current/deploying-with-ansible/reference.html#wazuh-agent
Agent to be installed on Ubuntu 14.04

Received following error when running ansible-playbook wazuh-agent.yml:

The error appears to have been in '/etc/ansible/roles/ansible-wazuh-agent/tasks/main.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- import_tasks: "Windows.yml"
  ^ here

The error appears to have been in '/etc/ansible/roles/ansible-wazuh-agent/tasks/main.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- import_tasks: "Windows.yml"
  ^ here

**Comment by michaelkrieg** [comment]
Hi,

maybe your Ansible version is prior 2.4.
"import_tasks" is new in Ansible version 2.4.

Best,
Micha

**Comment by alphaDev23** [comment]
yes, that was the issue.  Updated to 2.7 from 2.3.x and it resolved the error.  Thank you. I appreciate your help.
