### ISSUE TITLE
No package matching 'opendistroforelasticsearch-1.13.2' is available

### ISSUE THREAD

**Issue by sm4rtk1dz** [wazuh/wazuh-ansible#657]
Hi! I'm having issues with the packages of OpenDistro

````

TASK [../roles/opendistro/opendistro-elasticsearch : Add Opendistro repository]   
*******************************************************************************************
ok: [wazuh]

TASK [../roles/opendistro/opendistro-elasticsearch : Install OpenDistro]   
*******************************************************************************************
ok: [wazuh]

TASK [../roles/opendistro/opendistro-elasticsearch : Install OpenDistro]   
*******************************************************************************************
fatal: [wazuh]: FAILED! => {"changed": false, "msg": "No package matching 'opendistroforelasticsearch-1.13.2' is available"}
````
apparently there's no such package as ``opendistroforelasticsearch-1.13.2``?
Is there a way to fix this?

**Comment by sm4rtk1dz** [comment]
Hi! Nope i couldn't solve it, I was in a hurry so I ended up using the generic installer. 

I was working with the stable branch, tried the installation on many different servers just to test it out:

- Ubuntu
- Debian
- CentOS

I couldn't make it work on any of them, but for different reasons that unfortunately I wasn't able to report.

Yes I made a couple customizations just to see if I was able to run them, for example, I was running the playbooks from a different source than the one given in this repo and it failed due to relative path issues.  

Then as stated above i changed all the ``-{{ opendistro_version }}`` to nothing, to make the installer default to the version present in the apt cache.

As far as I understand the main bugs here were due to:
1) relative path issues
2) hardcoded versions

But I haven't dig deep enough to confirm.

**Comment by teddytpc1** [comment]
Hi @sm4rtk1dz.
Please use branch/tag `v4.2.4` to deploy with Ansible. I have tested from `stable` and got the same error. With `v4.2.4` works (I have tested it with Ubuntu, Debian and CentOS). I will create a new issue in order to resolve the error using `stable`. Thanks for reporting it.
Let me know if it works using `v4.2.4` please. I recommend to use a new VM/Server if you can.

**Comment by alberpilot** [comment]
I proceed to close this issue. Please don't hesitate to re-open if necessary.
