### ISSUE TITLE
Fix Molecule tests

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-ansible#661]
Analyze the reason why the tests are failing and fix them.

**Comment by pyToshka** [comment]
Hi @teddytpc1 
I know how to quick fix molecule failing. 
Unfortunately I didn’t find full contribution guidelines. Should i create pr for master branch?

**Comment by teddytpc1** [comment]
The tests were fixed with [this PR](https://github.com/wazuh/wazuh-ansible/pull/771/).
