### ISSUE TITLE
Use Wazuh repositories to install opendistro

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-ansible#663]
We should use the Opendistro packages stored in the Wazuh repository instead of using the OD ones.

https://github.com/wazuh/wazuh-ansible/blob/1c6c235c5d6a436b84f25f31613fe678ddab22f2/roles/opendistro/opendistro-elasticsearch/tasks/Debian.yml#L25-L36

**Comment by alberpilot** [comment]
Solved with wazuh-indexer/dashboard and hosted filebeat.
