### ISSUE TITLE
Review API configuration parameters to match the new standard

### ISSUE THREAD

**Issue by Kondent** [wazuh/wazuh-ansible#691]
# Description
### As a part of the epic issue wazuh/wazuh#11414, we should review and modify (if needed) every reference to the API configuration to match the new standard.
---
As the issue wazuh/wazuh#11409 (PR wazuh/wazuh#11410) says, the `path` parameter at API configuration file is no longer needed and will be deprecated on a later version.
Plus, `key`, `cert` and `ca` are now filenames instead of a file path.
```
"https": {
	"enabled": True,
	"key": "server.key",
	"cert": "server.crt",
	"use_ca": False,
	"ca": "ca.crt",
	"ssl_protocol": "TLSv1.2",
	"ssl_ciphers": ""
},
```

# Changes

In this repository we found the following:

https://github.com/wazuh/wazuh-ansible/blob/a18e566029603aa871cf4849b599ff704b2d8863/roles/wazuh/ansible-wazuh-manager/templates/api.yaml.j2#L20-L22

https://github.com/wazuh/wazuh-ansible/blob/a18e566029603aa871cf4849b599ff704b2d8863/roles/wazuh/ansible-wazuh-manager/templates/api.yaml.j2#L11-L17

# Note
* This should be reviewed in more depth to make sure all configuration references are fixed.
* The wazuh API log file will be located at `/var/ossec/logs/api.log`, in other words the current log path won't be changed after this epic development.
* The same occurs to `key`, `cert` and `ca` file locations.

**Comment by teddytpc1** [comment]
The `api.yaml` does not longer exist in branch `4.3`. It was removed because it was not being used by the Ansible Playbooks.
The `api.yaml` used by the Ansible deployment is the default that comes with the wazuh-manager installation package.
