### ISSUE TITLE
Wrong template values 

### ISSUE THREAD

**Issue by shikuk** [wazuh/wazuh-ansible#692]
File https://github.com/wazuh/wazuh-ansible/blob/a18e566029603aa871cf4849b599ff704b2d8863/roles/wazuh/ansible-wazuh-manager/templates/var-ossec-etc-ossec-server.conf.j2
```
  {% if wazuh_manager_config.sca.day | length > 0 %}
    <day>yes</day>
  {% endif %}
  {% if wazuh_manager_config.sca.wday | length > 0 %}
    <wday>yes</wday>
  {% endif %}
  {% if wazuh_manager_config.sca.time | length > 0 %}
    <time>yes</time>
  {% endif %}
```
So we have
wazuh-modulesd: ERROR: (1241): Invalid day format: 'yes'.
wazuh-modulesd: ERROR: (1235): Invalid value for element 'wday': yes.

It seems we have to use smth like this 
```
  {% if wazuh_manager_config.sca.day | length > 0 %}
    <day>{{ wazuh_manager_config.sca.day }}</day>
  {% endif %}
  {% if wazuh_manager_config.sca.wday | length > 0 %}
    <wday>{{ wazuh_manager_config.sca.wday }}</wday>
  {% endif %}
  {% if wazuh_manager_config.sca.time | length > 0 %}
    <time>{{ wazuh_manager_config.sca.time }}</time>
  {% endif %}
```
As referenced here
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-openscap.html

**Comment by c-bordon** [comment]
Hello, after some tests I was able to replicate the error you mention, and applying the correction you propose I see that it works correctly, I have generated a PR to apply the Fix.

Thank you very much for your contribution

**Comment by shikuk** [comment]
The same issue found for agent at 
https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-agent/templates/var-ossec-etc-ossec-agent.conf.j2

**Comment by c-bordon** [comment]
Thanks again shikuk, I was able to verify what you mention about the agent, and the same change should be applied.
 I already generated the PR to apply it
