### ISSUE TITLE
Fix ssl_cipher in api.yaml.j2

### ISSUE THREAD

**Issue by vegassor** [wazuh/wazuh-ansible#700]
Hi everyone! 
I stumbled upon an issue, when tried to install wazuh-manager 4.2.5.

I see the `api.yaml` file schema changed a bit in this PR. https://github.com/wazuh/wazuh/pull/10219/files
The `ssl_cipher` property is now `ssl_protocol`.

But jinja2 template for [api.yaml](https://github.com/wazuh/wazuh-ansible/blob/dd1ccf86803fae61e3c71a6de8e7e777688954a4/roles/wazuh/ansible-wazuh-manager/templates/api.yaml.j2#L17) does not take it into account, so I did end up with a bit broken config.

**Comment by teddytpc1** [comment]
Hi @vegassor.
I have tested the installation using tag `v4.2.5` from `wazuh-ansible` repo and the `api.yaml` file is the default one:
- [api.yaml.txt](https://github.com/wazuh/wazuh-ansible/files/7953558/api.yaml.txt)

It is not taking it from the `api.yaml.j2` template. In fact, the `api.yaml.j2` template was deleted for the upcoming release as it is not being used by Ansible. Can you:
- provide the playbook you are using? Please remove any sensitive information, such as IPs.
- tell me what branch/tag are you using?
- upload the api.yaml you are seeing after the install?

Thanks.

**Comment by alberpilot** [comment]
Hello @vegassor 

I proceed to close this issue, please don't hesitate to open it again if you need further assistance.

Regards,
Alberto R
