### ISSUE TITLE
Wazuh Manager Install Error

### ISSUE THREAD

**Issue by alexoslabs2** [wazuh/wazuh-ansible#703]
I tried install the wazuh manager using the wazuh-manager and wazuh-elastic_stack-single playbooks in the Debian 10 (Buster) but this error was displayed:

TASK [../roles/wazuh/ansible-wazuh-manager : Debian/Ubuntu | Install wazuh-manager] *************************************************
fatal: [192.168.100.173]: FAILED! => {"cache_update_time": 1644879681, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      **install 'wazuh-manager=4.4.0-1'' failed: E: Version '4.4.0-1' for 'wazuh-manager' was not found**\n", "rc": 100, "stderr": "E: Version '4.4.0-1' for 'wazuh-manager' was not found\n", "stderr_lines": ["E: Version '4.4.0-1' for 'wazuh-manager' was not found"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information..."]}

**Comment by verdx** [comment]
Hi @alexoslabs2 It looks like you have used the `master` branch, with the latest, unstable code. Please use the stable branch for the latest stable code or a tag if you want a specific version. For example, if you want to use version 4.2.5 use tag `v4.2.5`

**Comment by alberpilot** [comment]
hello @alexoslabs2 

I proceed to close this issue, please don't hesitate to open it again if you need further assistance. 

Regards, 
Alberto R
