### ISSUE TITLE
Adapt the Ansible deployment to use the new Wazuh indexer default ports. 

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-ansible#706]
As mentioned in https://github.com/wazuh/wazuh-packages/issues/1285, the Wazuh indexer must use the same default ports as elasticsearch. We need to change all deployment-involved files to 9200 and 9300 as default ports.

**Comment by teddytpc1** [comment]
These changes were pushed to the `732-indexer-dashboard` branch.
