### ISSUE TITLE
 Incorrect ansible distributed provision - Dashboard is installed along with indexer 

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-ansible#754]
### Description

During the manual testing of the [ansible distributed deployment](https://github.com/wazuh/wazuh-qa/issues/2821), we have detected that the wazuh-indexer is installed along with the dashboard even if this is not specified.

For example, using the following `/etc/ansible/hosts`:

```

[indexer]
172.31.83.248
172.31.89.49
172.31.86.85

[wazuh-master]
172.31.89.12

[wazuh-worker]
172.31.91.220

wi1 ansible_host=3.84.233.202 private_ip=172.31.83.248 indexer_node_name=node-1
wi2 ansible_host=3.95.162.15 private_ip=172.31.89.49 indexer_node_name=node-2
wi3 ansible_host=44.204.66.247 private_ip=172.31.86.85 indexer_node_name=node-3

dashboard  ansible_host=52.90.193.168 private_ip=172.31.86.15
manager ansible_host=54.208.18.40 private_ip=172.31.89.12
worker  ansible_host=54.159.7.40 private_ip=172.31.91.220

[wi_cluster]
wi1
wi2
wi3
```

We should expect to have a 3 node Wazuh indexer cluster, but another node is created (node-6) in the dashboard host:
```
[root@ip-172-31-83-248 centos]# curl -k -u admin:changeme https://172.31.83.248:9200/_cat/nodes?v
ip            heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
172.31.86.85            35          81   4    0.00    0.07     0.16 dimr      -      node-3
172.31.83.248           33          82   3    0.00    0.07     0.17 dimr      -      node-1
172.31.89.49            53          82   4    0.00    0.06     0.17 dimr      *      node-2
172.31.86.15            53          82   4    0.00    0.06     0.17 dimr      *      node-6
```

If this is the expected behavior,  we need to improve the documentation about this issue. For example in this block:
```
The YAML file wazuh-production-ready.yml will provision a production-ready distributed Wazuh environment. We will add the public and private IP addresses of the endpoints where the various components of the cluster will be installed to the Ansible hosts file. For this guide, architecture includes 2 Wazuh nodes, 3 Wazuh indexer nodes and **a mixed Wazuh dashboard node**.
```
It does not explain what a mixed Wazuh dashboard node is.

Also, the `wazuh-dashboard` role does not says anything about wazuh-indexer deployment.

In addition, it is not possible to deploy a dedicated server for the wazuh-dashboard?

**Comment by c-bordon** [comment]
In principle, this is expected behavior, if we need to update the documentation to specify that a Data Indexer node is raised in the dashboard node, however, in the issue: https://github.com/wazuh/wazuh -ansible/issues/755 a problem of this deployment is being worked on, after the solution of that issue we will see if something needs to be modified or not in this deployment

**Comment by teddytpc1** [comment]
Hi @Rebits. 
Can we close this issue?
