### ISSUE TITLE
Remove some Wazuh cluster variables

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-ansible#766]
| Epic | Docu issue |
|--|--|
|https://github.com/wazuh/wazuh/issues/7108|https://github.com/wazuh/wazuh-documentation/issues/5215|

## Description
It is intended to make the Wazuh cluster enabled and running by default. This development will be done in: 
- https://github.com/wazuh/wazuh/issues/7108

As a consequence, certain configuration options will disappear. How each option will be affected can be seen in https://github.com/wazuh/wazuh/issues/13351 and https://github.com/wazuh/wazuh/issues/13353. As a summary, the main changes are these:
- [**disabled**](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html#disabled): Removed.
- [**name**](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html#name): Removed
- [**node_name**](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html#name): The hostname will be used by default.
- [**node_type**](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html#node-type): Do not change.
- [**key**](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html#key): Removed.
- [**bind_addr**](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html#bind-addr): A list of addresses will be accepted.
- [**nodes**](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html#nodes): `127.0.0.1` should be used by default. 
- [**hidden**](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html#hidden): Do not change.

It will be necessary to update or remove in the Ansible module those variables that are affected:
https://github.com/wazuh/wazuh-ansible/blob/a580ec37926905f6acb92f9762d95fa379fe4f61/molecule/distributed-wazuh-odfe/group_vars/managers.yml#L14-L19

There are more places with references to these variables, so it will be necessary to search and change all of them and check that the module works correctly after that.

**Comment by teddytpc1** [comment]
The changes were tested with `4.4`. It failed because some removed parameters are required for that version, but the playbook succeeds until it tries to start the Wazuh manager.

The PR is ready for review and the automatic tests will fail because there are no `4.5.0` packages in `pre-release`.

**Comment by alberpilot** [comment]
This issue goes to blocked due to the main development delay.

**Comment by teddytpc1** [comment]
This will be handled as part of the `5.0.0` release changes.
