### ISSUE TITLE
Conflicts of configuration and monitoring of non-existent directories

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-ansible#77]
Hello team,

We are going to proceed with the creation of two issues related to each other.

The problems detected are the following:

- Conflict between agent configuration in **/var/ossec/etc/ossec.conf** and manager pushed configuration in **/var/ossec/etc/shared/default/agent.conf**. 

     **CONF**

   - /ansible-wazuh-agent/templates/var-ossec-etc-ossec-agent.conf.j2

     https://github.com/wazuh/wazuh-ansible/blob/master/ansible-wazuh-agent/templates/var-ossec-etc-ossec-agent.conf.j2#L94-L99

   - /ansible-wazuh-agent/defaults/main.yml

     https://github.com/wazuh/wazuh-ansible/blob/master/ansible-wazuh-agent/defaults/main.yml#L49-L53

    **SHARED**

   - /ansible-wazuh-manager/templates/var-ossec-etc-shared-agent.conf.j2

      https://github.com/wazuh/wazuh-ansible/blob/master/ansible-wazuh-manager/templates/var-ossec-etc-shared-agent.conf.j2#L12-L17

   - /ansible-wazuh-manager/defaults/main.yml

      https://github.com/wazuh/wazuh-ansible/blob/master/ansible-wazuh-manager/defaults/main.yml#L204-L208

- Monitoring of non-existent directories. In operating systems like Ubuntu 16, Ubuntu 18 and other Debian, there are not the following directories to monitor. In CentOS 7 some of they exist. 

     - location: '/var/log/messages'
     - location: '/var/log/secure'
     - location: '/var/log/maillog'
     - location: '/var/log/httpd/error_log'
     - location: '/var/log/httpd/access_log'

The problem is that there are events that we are not collecting, such as those belonging to the **/var/logs/auth.log** file. Additionally, there are duplicate directories in the shared agent.conf.

   - https://github.com/wazuh/wazuh-ansible/blob/master/ansible-wazuh-agent/defaults/main.yml#L88-L91

   - https://github.com/wazuh/wazuh-ansible/blob/master/ansible-wazuh-manager/defaults/main.yml#L213-L216

As a quick response we need to delete the directories monitored by syscheck duplicates, proceeding to remove the directories from Shared agent.conf. 

It is also necessary to remove duplicate localfile entries in the shared configuration, as well as add entries to monitor events such as those stored in **/var/logs/auth.log**. 

Regards,

Alfonso

**Comment by cadoming** [comment]
Hi,

This Issue is solved in the PR #90 so I'm going to proceed to close it. Thank you @SitoRBJ for your work.

Regards,
Carlos
