### ISSUE TITLE
install wazuh4.3 with ansible error!

### ISSUE THREAD

**Issue by Hello-Linux** [wazuh/wazuh-ansible#783]
The kibana error is 

INFO: Template found for the selected index-pattern title [wazuh-alerts-*]: no
ERROR: No template found for the selected index-pattern title [wazuh-alerts-*]"
And the filebeat log show error is

"[publisher_pipeline_output]        pipeline/output.go:154        Failed to connect to backoff(elasticsearch(https://172.16.1.234:9200)): 401 Unauthorized: Unauthorized
[publisher_pipeline_output]        pipeline/output.go:145        Attempting to reconnect to backoff(elasticsearch(https://172.16.1.234:9200)) with 827 reconnect attempt(s)"

But I run the curl command on filebeat node, the command show
```
[root@wazuh-002 ~]# curl --insecure -u admin:z#Iudgh  https://172.16.1.234:9200/_cat/health
1653961981 01:53:01 wazuh green 3 3 true 7 4 0 0 0 0 - 100.0%
```
 
the elasticsearch is working,and why filebeat show 401 Unauthorized: Unauthorized???????
![002](https://user-images.githubusercontent.com/17851645/171025637-4a2bd13f-05bc-46f9-92a7-1952c5d14990.png)

**Comment by teddytpc1** [comment]
Hi @Hello-Linux.
Can you share or check the username and password configured in the `/etc/filebeat/filebeat.yml` file? It should match the ones you are using for the `curl` command.
Also run the following command and share the output please:
`filebeat test output`

**Comment by teddytpc1** [comment]
This issue will be closed because of inactivity. @Hello-Linux feel free to reopen it.
