### ISSUE TITLE
Change api password value to be enclosed in double quotes

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-ansible#834]
We need to modify the wazuh.yml template so that the password is enclosed in double quotes.

The current format can produce an error if the password begins with *, since yaml would recognize that value as an alias and the health check will fail, for more information, see the issue https://github.com/wazuh/wazuh-packages/issues/1804

https://github.com/wazuh/wazuh-ansible/blob/68718a0a55765334837a0402f86ccf72ac891843/roles/wazuh/wazuh-dashboard/templates/wazuh.yml.j2#L133

Must set the value to:

```
password: "password"
```

**Comment by teddytpc1** [comment]
@vcerenu check this [PR](https://github.com/wazuh/wazuh-ansible/pull/795/files).

**Comment by teddytpc1** [comment]
I have tested an AIO deployment with ansible and it is working fine with a complex password: `.S3cur3Pa55w0rd*-`.
