### ISSUE TITLE
Template wazuh-config.yml.j2 missing for "local action" task during indexer installation

### ISSUE THREAD

**Issue by komodikkio** [wazuh/wazuh-ansible#897]
Hi all.
I'm trying to use this to setup a 4.3.10 on 3 nodes
1 indexer
1 dashboard
1 master+filebeat

When i run the wazuh-indexer.yml playbook, the task "Local action | Prepare the certificates generation template file" fails because the template wazuh-config.yml.j2 is missing.
I couldn't find it in my local files or here on the repo.
Am i doing something wrong or did i misunderstood something?
Do i have to manually create the jinja template for this?

Thanks in advance for any help or clarification.

**Comment by teddytpc1** [comment]
Hi @komodikkio.
The jinja template is in the repository here: `roles/wazuh/wazuh-indexer/templates/config.yml.j2`.
 
1. Can you share a screenshot of the error?
2. What branch are you using? You should be using branch `4.3` or tag `v4.3.10`

**Comment by teddytpc1** [comment]
Seems that you are not using `v4.3.10` code. Check this out in `main` branch:

- https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/wazuh-indexer/defaults/main.yml#L29

The value for `indexer_sec_plugin_conf_path` is `/etc/wazuh-indexer/opensearch-security`.
But is `v4.3.10` is `/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig`:

- https://github.com/wazuh/wazuh-ansible/blob/v4.3.10/roles/wazuh/wazuh-indexer/defaults/main.yml#L29

Please make sure you are using the right branch. And yes, it is better if you clone and checkout, but it should be the same.

**Comment by komodikkio** [comment]
hi @teddytpc1 
your suggestions pointed me in the right direction, I was porting the variables in group_vars from the wrong branch.
Fixed that, the indexer installed without error, I'm going ahead with the master server setup now
Thanks a lot for all the hints you provided me
