### ISSUE TITLE
Question about Wazuh Agent on Ubuntu 20.04 server

### ISSUE THREAD

**Issue by brmb** [wazuh/wazuh-ansible#904]
Hello, I have a question regarding Wazuh Agent reliability and known issues on Ubuntu 20.04 version (_would appreciate the same on 22.04 as well_). In this [code section](https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-agent/defaults/main.yml#L42), 20.04 is missing, so I assume its not stable or it just applies 18.04 profile? 

Thanks in advance!

**Comment by rauldpm** [comment]
Hello @brmb! Thanks for your contribution, you are absolutely right, in an installation of the Wazuh agent in Ubuntu 20 and Ubuntu 22 the profiles correspond to the said systems so the `wazuh-ansible` deployment must be adapted with these two systems too.

- Ubuntu 20

```
<config-profile>ubuntu, ubuntu20, ubuntu20.04</config-profile>
```

- Ubuntu 22

```
<config-profile>ubuntu, ubuntu22, ubuntu22.04</config-profile>
```

I have opened the following issue https://github.com/wazuh/wazuh-ansible/issues/910 to be able to work on the necessary changes

**Comment by rauldpm** [comment]
Issue closed due to inactivity, please feel free to open another issue or reopen it if necessary.
