### ISSUE TITLE
Windows installer md5 hash incorrect

### ISSUE THREAD

**Issue by justusbunsi** [wazuh/wazuh-ansible#928]
Hi, the referenced md5 checksum for windows installer on tag [v4.4.3](https://github.com/wazuh/wazuh-ansible/releases/tag/v4.4.3) seem to not match the currently downloadable installer.

Reference in release: 921dee671c223ac7e5424d2ce5d54dfe
Actual checksum (as of 2023-05-30): cd6e738c0c1ee3a30a731611c74dd3cd

Are there binary redeploys that were not taken into account for the Ansible script? I've noticed that for v4.4.1 in the past as well.

Thanks for clarification.

**Comment by rauldpm** [comment]
The fix has been applied, please don't hesitate to let us know about any other issues, thanks!
