### ISSUE TITLE
Wazuh Agent installation on a different path

### ISSUE THREAD

**Issue by brmb** [wazuh/wazuh-ansible#941]
Currently it is not possible to install Wazuh Agent via ansible playbook on a different path.
It is only possible with [install.sh](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html) script which is not convenient when deploying Wazuh Agent on hundreds of servers.
Changing `wazuh_dir` [variable](https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-agent/defaults/main.yml#L58) does not help much.

Default path is `/var/ossec`, I want to install it on `/opt/ossec` because `/var/ossec` is already occupied by another tool.

According to Julio G. from [Slack](https://wazuh.slack.com/archives/C0A933R8E/p1687520559619669?thread_ts=1684247038.259979&cid=C0A933R8E) Wazuh Community:
> Regarding the ansible script we have, it it designed to install the normal package (not the source one ) that we are using to install on a different path, I think that is why it is not working  as expected

---

Can this be fixed/improved so that `wazuh_dir` or another variable would influence Wazuh Agent installation path?

**Comment by rauldpm** [comment]
Hello @brmb 

As @gascoj has mentioned, the installation path of the package is defined by the package itself, that is, it is defined when building the package, which by default is `/var/ossec/`

- https://github.com/wazuh/wazuh-packages/blob/master/rpms/generate_rpm_package.sh#L39

```
INSTALLATION_PATH="/var/ossec"
```

If you want to install a package in another directory you must create your own modified package using the `wazuh-packages` repository as indicated in the documentation, for example, for RPM it would be: https://documentation.wazuh.com/current/development/packaging/generate-rpm-package.html

In each system you will see that there is a parameter where you can set the desired path, in the case of RPM it is `-p, --path <path>`, an example would be:

```
./generate_rpm_package.sh -b v4.4.4 --packages-branch v4.4.4 -t agent -a x86_64 -p /opt/ossec
```

So once you have the package, you must modify the deployment to use the package you have generated.

**Comment by brmb** [comment]
@rauldpm @gascoj do you have a guide on how to configure Docker in order for this to work?
Trying this from newest MacOS:

```
➜  rpms git:(v4.4.1) brew list | grep docker
docker
➜  rpms git:(v4.4.1) docker --version
Docker version 24.0.2, build cb74dfcd85
➜  rpms git:(v4.4.1) ./generate_rpm_package.sh -b v4.4.1 --packages-branch v4.4.1 -t agent -a x86_64 -p /opt/ossec
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by rauldpm** [comment]
How did you install Docker? If you run `docker ps`, what output do you get?

As the message says, do you have Docker running? Please make sure you have Docker started in order to use it.

**Comment by brmb** [comment]
Installed it with `brew install docker` at first, solved it with `brew install --cask docker`. 
However, now I'm getting this:

![Screenshot 2023-06-29 at 09 55 30](https://github.com/wazuh/wazuh-ansible/assets/51971082/ecb8ed6b-a4e3-4691-9c51-de87dec1c35a)

```
➜  rpms git:(v4.4.1) ./generate_rpm_package.sh -b v4.4.1 --packages-branch v4.4.1 -t agent -a x86_64 -p /opt/ossec
[+] Building 0.6s (3/3) FINISHED
 => [internal] load .dockerignore                                                                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                                                                             0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                        0.0s
 => => transferring dockerfile: 3.01kB                                                                                                                                                                                      0.0s
 => ERROR [internal] load metadata for docker.io/library/centos:6                                                                                                                                                           0.6s
------
 > [internal] load metadata for docker.io/library/centos:6:
------
Dockerfile:1
--------------------
   1 | >>> FROM centos:6
   2 |
   3 |     # Install all the necessary tools to build the packages
--------------------
ERROR: failed to solve: centos:6: no match for platform in manifest sha256:a93df2e96e07f56ea48f215425c6f1673ab922927894595bb5c0ee4c5a955133: not found (did you mean centos?)
```

**Comment by rauldpm** [comment]
It seems you are running a similar issue to the one reported in this issue: https://github.com/wazuh/wazuh-packages/issues/653

Are you using an `Intel` or `ARM` machine?

Note that the `centos:6` image has no option on ARM architecture:

- https://hub.docker.com/layers/library/centos/6/images/sha256-498c1320b2574fc5bbf897768ffd2c510edf0af3bc4c561aa1836f64845c1c27?context=explore

To build an AMD package you should use a native AMD system to ensure maximum compatibility, however in principle it is possible that it could be built using the `--platform=linux/amd64` parameter.

```
user@M1Mac ~ % docker build -t "wa-941" .
[+] Building 1.5s (3/3) FINISHED                                                
 => [internal] load build definition from Dockerfile                       0.1s
 => => transferring dockerfile: 70B                                        0.1s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for docker.io/library/centos:6          1.4s
------
 > [internal] load metadata for docker.io/library/centos:6:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:a93df2e96e07f56ea48f215425c6f1673ab922927894595bb5c0ee4c5a955133: not found
user@M1Mac ~ % docker build -t "wa-941" . --platform=linux/amd64 
[+] Building 10.7s (6/6) FINISHED                                                                                                                                                                                  
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.0s
 => => transferring dockerfile: 36B                                                                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/centos:6                                                                                                                                                   1.0s
 => [1/2] FROM docker.io/library/centos:6@sha256:a93df2e96e07f56ea48f215425c6f1673ab922927894595bb5c0ee4c5a955133                                                                                             9.1s
 => => resolve docker.io/library/centos:6@sha256:a93df2e96e07f56ea48f215425c6f1673ab922927894595bb5c0ee4c5a955133                                                                                             0.0s
 => => sha256:a93df2e96e07f56ea48f215425c6f1673ab922927894595bb5c0ee4c5a955133 530B / 530B                                                                                                                    0.0s
 => => sha256:3688aa867eb84332460e172b9250c9c198fdfd8d987605fd53f246f498c60bcf 529B / 529B                                                                                                                    0.0s
 => => sha256:5bf9684f472089d6d5cb636041d3d6dc748dbde39f1aefc374bbd367bd2aabbf 2.62kB / 2.62kB                                                                                                                0.0s
 => => sha256:ff50d722b38227ec8f2bbf0cdbce428b66745077c173d8117d91376128fa532e 69.84MB / 69.84MB                                                                                                              6.7s
 => => extracting sha256:ff50d722b38227ec8f2bbf0cdbce428b66745077c173d8117d91376128fa532e                                                                                                                     2.2s
 => [2/2] RUN echo "AMD64"                                                                                                                                                                                        0.4s
 => exporting to image                                                                                                                                                                                        0.0s
 => => exporting layers                                                                                                                                                                                       0.0s
 => => writing image sha256:e7e5e321b3dc2449aaf04d9869c9c276d003b9e10d74c3ce2fdc8223995a4310                                                                                                                  0.0s
 => => naming to docker.io/library/wa-941                                                                                                                                                                     0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
```

For this, you must modify the following line to add the said parameter:

- https://github.com/wazuh/wazuh-packages/blob/aea18f9752e693d6e4426d3a0dcd12b3b47d8e9a/rpms/generate_rpm_package.sh#L89

```
docker build -t ${CONTAINER_NAME} ${DOCKERFILE_PATH} || return 1
```

Also, you will have to modify the `docker run` line to add the following parameter `--platform linux/amd64`, if not, you will receive a message like:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

- https://github.com/wazuh/wazuh-packages/blob/aea18f9752e693d6e4426d3a0dcd12b3b47d8e9a/rpms/generate_rpm_package.sh#L93

```
    docker run -t --rm -v ${OUTDIR}:/var/local/wazuh:Z \
        -v ${CHECKSUMDIR}:/var/local/checksum:Z \
        -v ${LOCAL_SPECS}:/specs:Z \
        ${CUSTOM_CODE_VOL} \
        ${CONTAINER_NAME} ${TARGET} ${BRANCH} ${ARCHITECTURE} \
        ${JOBS} ${REVISION} ${INSTALLATION_PATH} ${DEBUG} \
        ${CHECKSUM} ${PACKAGES_BRANCH} ${USE_LOCAL_SPECS} ${SRC} \
        ${LEGACY} ${USE_LOCAL_SOURCE_CODE} ${FUTURE}|| return 1
```

**Comment by rauldpm** [comment]
Glad to see you managed to do it!

> I assume the procedure is the same with DEB package, will try and let you know later this week.

Yes, the procedure should be the same but following the instructions for Debian packages.

> How would I go about upgrading Wazuh Agent in the future with such deployments? Would it work by instructing it via Wazuh Manager or I would need to completely rebuild the RPM/DEB package and install a new version that way?

As you are using a package with a custom installation path, you need to create a new package of the version you want to upgrade and perform the upgrade with that package.

By default, the manager performs the remote upgrade with the package available in production through `agent_upgrade`, which uses `.wpk` packages, if you want to use this method, you will have to generate the WPK package for Linux and perform the upgrade remotely from the manager itself

For more information about the `agent_upgrade` module I leave this link: https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/agent-upgrade-module.html

```
The agent upgrade module is responsible for carrying out the entire agent upgrade process remotely:
- On the manager side, it validates, downloads, and/or sends the WPK files to the agents.
- On the agent side, it processes the received commands and sends a notification to the manager after an upgrade process has been accomplished.
```

How to generate a WPK package: https://documentation.wazuh.com/current/development/packaging/generate-wpk-package.html, look at the `-p` option

```
-p, --path <path> [Optional] Installation path for the package. By default: /var.
```

```
./generate_wpk_package.sh -t linux -b v4.4.4 -d /tmp/wpk -k /tmp/keys -o LinuxAgent.wpk
```

How to install a custom WPK package: https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/install-custom-wpk.html

```
/var/ossec/bin/agent_upgrade -a 001 002 -f path/to/myagent.wpk -x upgrade.sh
```

I also leave you the documentation about `agent_upgrade`, so that you can see the options available: https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html

**Comment by rauldpm** [comment]
Issue closed due to inactivity, please feel free to open another issue if necessary

**Comment by brmb** [comment]
Hi @rauldpm 👋🏼 
I'm facing an issue when building RPM/DEB packages this time. For example:
![Screenshot 2024-04-28 at 16 50 45](https://github.com/wazuh/wazuh-ansible/assets/51971082/8daa0d4c-0510-4963-92eb-9f2a025f7121)

Do you have any ideas what could be wrong? I modified the `generate_rpm_package.sh` & `generate_debian_package.sh` like this:
<img width="686" alt="Screenshot 2024-04-28 at 16 53 27" src="https://github.com/wazuh/wazuh-ansible/assets/51971082/05151fd4-260b-4db0-ab89-99fe87683680">
