### ISSUE TITLE
Playbooks default configuration

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-ansible#95]
Hello all,
it looks like Wazuh manager and agents configuration is being built using older Wazuh versions tags and behavior assumptions.

We should review how this works and what we want to include as a default configuration, updating it to Wazuh current release.

Regards.

**Comment by cadoming** [comment]
Hi @havidarou,

I just made the PR #106  doing the changes you propouse in this Issue. Thank you for your work.

Regards,
Carlos

**Comment by SitoRBJ** [comment]
Hello team,

The PR #106 solves this issue.

Great job @cadoming.

Kind regards,

Alfonso Ruiz-Bravo
