### ISSUE TITLE
Windows installer md5 hash incorrect (multiple releases)

### ISSUE THREAD

**Issue by justusbunsi** [wazuh/wazuh-ansible#976]
Hi, the referenced md5 checksum for windows installer on tags [v4.4.5](https://github.com/wazuh/wazuh-ansible/releases/tag/v4.4.5) and [v4.5.0](https://github.com/wazuh/wazuh-ansible/releases/tag/v4.5.0) does not match the currently downloadable installer.

**v4.4.5**

Reference in release: a03806b7302767d0470d65d3f103fabb (which matches the one from v4.4.4)
Actual checksum (as of 2023-08-09): 396833b72a865be4b693f18ee2e34cde

![image](https://github.com/wazuh/wazuh-ansible/assets/61625851/24ed350f-54e4-44b6-96f1-6756c64aae99)

**v4.5.0**

Reference in release: a03806b7302767d0470d65d3f103fabb (still which matches the one from v4.4.4)
Actual checksum (as of 2023-08-16): fd53c0afc26394ef5ce6a0922186de29

![image](https://github.com/wazuh/wazuh-ansible/assets/61625851/85a5a88e-585c-4dd6-a3f8-33c70d630686)

As it seem to be a reoccurring issue, is there anything missing in the release workflow? (see #928)

**Comment by davidcr01** [comment]
Hello.

Two PRs have been created to fix this problem:
- https://github.com/wazuh/wazuh-ansible/pull/995
- https://github.com/wazuh/wazuh-ansible/pull/994

This mistake is done because is necessary to check the MD5 checksums after the packages are generated, and then, change them before releasing the definitive tag.

Hope it helps. 
Regards, David.

**Comment by justusbunsi** [comment]
Thanks for fixing the releases. I can confirm that it now works.

@davidcr01 anything I can help with, so that the mistake doesn't happen in the future again?

**Comment by davidcr01** [comment]
Thanks, but no further help from you is needed. If your problem is fixed, I assume I can close this issue for now.
